<?php
	// Doctype
	echo $this->doctype('HTML5');
	// URL
	$base_url_full = $this->app()->getBaseUrl(true);
	$base_url = $this->app()->getBaseUrl();
	$public_url = $this->app()->getPublicUrl();
	$back_url = $this->app()->getAreaUrl('back');
	$front_url = $this->app()->getAreaUrl('front');
	$script_url = $public_url.'/scripts';
	$this->url()->renege('route','back');
	// Identity
	$Identity = $this->app()->getUser();
?><html>
<head>
    <?= $this->app()->headMeta() ?>
    <?= $this->app()->headTitle() ?>
    <?= $this->app()->headLink() ?>
    <?= $this->app()->headStyle() ?>
</head>
<body>
    <?
		$headScript = $this->app()->headScript();
		if ( APPLICATION_ENV !== 'development' )
			$headScript
				// GSFN
		    	->offsetSetFile(10,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
		    	->offsetSetScript(11,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
				;
	    echo $headScript;
    ?>
        <div id="wpwrap">
            <div id="wpcontent">
                <div id="wphead">
                    <!--<img id="header-logo" src="edit-pages.php_files/blank.gif" alt="" height="32" width="32">-->
                    <h1 id="site-heading"><a href="<?=$base_url_full?>" title="Visit Site">
                    	<span id="site-title"><?=$this->app()->getConfig('site.name')?></span>
                    	<em id="site-visit-button">Visit Site</em>
                    </a></h1>
                    <div id="wphead-info">
                        <div id="user_info">
                            <p>
                                User: <?=delve($Identity,'displayname')?>
                                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                                | <a href="<?=$this->url(array('action'=>'logout'),'back',true)?>" title="Log Out">Log Out</a>
                            </p>
                        </div>
	                    <?=true?'':$this->app()->getNavigationMenu('back.fav')->setPartial(array('navigation/favorites.phtml', 'default'))->render()?>
                    </div>
                </div>
                <div id="wpbody">
					<?
					try {
						echo $this->app()->getNavigationMenu('back.main')->setPartial(array('navigation/menu.phtml', 'default'))->render();
					}
					catch ( Exception $e ) {
						echo $e->getMessage();
						die;
					}
					?>
					<div id="wpbody-content">
                        <?= $this->layout()->content?>
                        <div class="clear">
                        </div>
                    </div>
                    <!-- wpbody-content -->
                    <div class="clear">
                    </div>
                </div>
                <!-- wpbody -->
                <div class="clear">
                </div>
            </div>
            <!-- wpcontent -->
        </div>
        <!-- wpwrap -->
        <div id="footer">
            <p id="footer-left" class="alignleft">
                <span id="footer-thankyou">Thank you for creating with <a href="<?=$this->url(array(),'balcmshome',true)?>">balCMS</a>.</span>
                | <a href="<?=$this->url(array(),'balcmsdocs',true)?>">Documentation</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>">Support</a>
            </p>
            <p id="footer-upgrade" class="alignright">
                Version <?=$this->app()->getConfig('site.version')?>
            </p>
            <div class="clear">
            </div>
        </div>
	</body>
</html>