<?php
	// Doctype
	echo $this->doctype('HTML5');
	// URL
	$this->url()->renege('route','back');
?>
<html>
<head>
    <?= $this->app()->headMeta() ?>
    <?= $this->app()->headTitle() ?>
    <?= $this->app()->headLink() ?>
    <?= $this->app()->headStyle() ?>
</head>
</head>
<body>
    <?
		$headScript = $this->app()->headScript();
		if ( APPLICATION_ENV !== 'development' )
			$headScript
				// GSFN
		    	->offsetSetFile(10,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
		    	->offsetSetScript(11,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
				;
	    echo $headScript;
	?>
	<?=$this->layout()->content?>
</body>
</html>