<?php
	# Doctype
	echo $this->doctype('HTML5');
	# URLs
	$this->url()->renege('route','front');
	$baseUrl = $this->app()->getBaseUrl();
	# Browser
	$unsupportedBrowser = $this->app()->isBrowser('ie',array('<=','8'));
	# User
	$User = $this->app()->getUser();
	# Tags
	$Tags = $this->app()->fetchRecords('TaggableTag');
	# Misc
	$gsfn = $this->app()->getConfig('bal.gsfn.company');
?><html class="<?=$this->app()->getHtmlClassAttribute()?>">
<head>
	<!-- Google Chrome Frame -->
	<meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1" />
	<!-- Header -->
    <?= $this->app()->headMeta() ?>
    <?= $this->app()->headTitle() ?>
    <?=
		$this->app()->headLink(array(
			'minify' => true,
			'editor' => false
		))
	?>
    <?= $this->app()->headStyle() ?>
</head>
<body>

	<!-- Header -->
    <?
    	# Prepare
		$scripts = array(
			'minify' => true,
			'json' => false,
			'editor' => false,
			'jquery_ui' => false,
			'jquery_lightbox' => false,
			'syntax_highlighter' => false,
			'jquery_ajaxy' => false
		);
		# Include
		$headScript = $this->app()->headScript($scripts);
		echo $headScript;
	?>
	
	<!-- Top Bar -->
	<div id="top"></div>
	
	<!-- Wrap -->
	<div id="wrap">
		
		<!-- Header -->
		<div class="header" id="header">
			<h1>
				<a href="<?=$baseUrl?>">
					<?=$this->app()->getConfig('site.name')?>
				</a>
			</h1>
			<ul class="rss">
				<li>
					<a href="<?=$baseUrl?>/feed/rss">
						Subscribe via RSS
					</a>
				</li>
			</ul>
		</div>
		
		<!-- Main Menu -->
		<div id="main-menu">
			<?=$this->app()
				->getNavigationMenu('front.menu')
				->setTemplate('<span>$label</span>')
				->setUlClass('menu')
				->render()?>
			</ul>
		</div>
		
		<!-- Content -->
		<div id="content">
			
			<!-- Article -->
			<div class="sl-a">
				<div class="sl-t"></div>
				<div class="sl">
					<?=$this->log()->render()?>
					<?=$this->layout()->content?>
				</div>
				<div class="sl-b"></div>
			</div>
			
			<!-- Sidebar -->
			<div class="sr-a">
				<div class="sr-t"></div>
				<div class="sr">
					
					<!--Search -->
					<div class="search-all">
						<form id="search" action="<?=$this->url()->action('search')->search()->toString()?>" method="post" class="search">
							<label for="search-query" id="search-header">
				                Search:
				            </label>
							<?=$this->formText('search[query]',delve($this,'search.query'))?>
							<?=$this->formSubmit('search[submit]','Search',array('class'=>'button white small'))?>
						</form>
					</div>
					
					<!-- Categories Widget -->
					<div class="categ-all">
						<?
							$Featured = $this->app()->fetchRecords('Content',array(
								'fetch' => 'simplelist',
								'featured' => true
							));
							echo $this->partial('partials/nav-content.phtml',array(
								'title' => 'Featured Content',
								'class' => 'categ',
								'Items' => $Featured
							));
						?>
					</div>
					
					<!-- Recent Widget -->
					<div class="widget">
						<?
							$Recent = $this->app()->fetchRecords('Content',array(
								'fetch' => 'simplelist',
								'recent' => true,
								'limit' => 7
							));
							echo $this->partial('partials/nav-content.phtml',array(
								'title' => 'Recently Updated',
								'class' => 'widget-all',
								'Items' => $Recent
							));
						?>
					</div>
					
					<!-- Archives Widget -->
					<div class="widget tags">
						<?=$this->partial('partials/nav-tags.phtml',array(
							'title' => 'Categories',
							'class' => 'widget-all',
							'Items' => $Tags
						))?>
					</div>
				</div>
				<div class="sr-b"></div>
			</div>
		</div>
		
		<!-- Footer -->
		<div id="footer">
			<p class="theme">
				Proudly produced by <a href="http://www.balupton.com/" rel="developer">Benjamin Lupton</a>
				<span style="color:#CCC">and <a href="http://designdisease.com/" rel="designer" style="color:#CCC">Design Disease</a></span>
			</p>
		</div>
	</div>

	<!-- App Footer -->
	<?=$this->app()->footer()?>
</body>
</html>