<?
	// URLs
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	//
	$ContentCrumb = delve($this,'ContentCrumb');
	$ContentList = delve($this,'ContentList');
	// Type
	$type = delve($this,'type','content');
	$Type = ucfirst($type);
	// Title
	$this->headTitle()->append($Type);
?><div class="wrap">
	<!-- Edit Button -->
    <div id="icon-edit-pages" class="icon32">
        <br/>
    </div>
	<!-- Header -->
    <h2>
		<a href="<?=$this->url()->action('content-list')?>"><?=$Type?> List</a>
		<? foreach ( $ContentCrumb as $_Content ): ?>
			&raquo; <a href="<?=$this->url()->action('content-list')->item($_Content)?>"><?=delve($_Content,'title')?></a>
		<? endforeach; ?>
		<a class="button add-new-h2" href="<?=$this->url()->action('content-new')?>">Create New</a>
	</h2>
    <!-- Filters -->
    <form id="posts-filter" action="<?=$this->url()->action('content-list')->search()?>" method="post">
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="search-query">
                Search:
            </label>
			<?=$this->formText('search[query]',delve($this,'search.query'),array())?>
			<?=$this->formSubmit('search[submit]','Search',array('class'=>'button'))?>
        </p>
	</form>
    <!-- Listing -->
    <form action="<?=$this->url()->action('content-list')?>" method="get">
        <div class="clear">
        </div>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        Title
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Description
                    </th>
                    <th scope="col" id="author" class="manage-column column-author" style="">
                        Author
                    </th>
                    <th scope="col" id="author" class="manage-column column-tags" style="">
                        Tags
                    </th>
					<!--<th scope="col" id="comments" class="manage-column column-comments num" style="">
                        <div class="vers">
                            <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                        </div>
                    </th>-->
                    <th scope="col" id="date" class="manage-column column-date" style="">
                        Date
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        Title
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Description
                    </th>
                    <th scope="col" id="author" class="manage-column column-author" style="">
                        Author
                    </th>
                    <th scope="col" id="author" class="manage-column column-tags" style="">
                        Tags
                    </th>
					<!--<th scope="col" id="comments" class="manage-column column-comments num" style="">
                        <div class="vers">
                            <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                        </div>
                    </th>-->
                    <th scope="col" id="date" class="manage-column column-date" style="">
                        Date
                    </th>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="content-list">
            	<? foreach ( $ContentList as $_Content ): ?>
            	<?
					$_Content_id = delve($_Content,'id');
					$_Content_title = delve($_Content,'title');
					$_Content_code = delve($_Content,'code');
					$_Content_updated_at = delve($_Content,'updated_at');
					$_Content_Avatar = delve($_Content,'Avatar');
					$_Content_Tags = delve($_Content,'Tags');
					$_Content_Author = delve($_Content,'Author');
            		$contentUrl = $this->url()->content($_Content)->toString();
            		$contentOpenUrl = $this->url()->action('content-list')->item($_Content)->toString();
            		$contentEditUrl = $this->url()->action('content-edit')->item($_Content)->toString();
            		$contentDeleteUrl = $this->url()->action('content-delete')->item($_Content)->toString();
            	?>
                <tr id="content-<?=$_Content_id?>" class="<?=$this->cycle(array('','alternate'), 'ContentTree')->next()?>">
                	<td class="column-icon media-icon">
						<a title="View <?=$_Content_title?>" href="<?=$contentUrl?>">
							<? if ( $_Content_Avatar ) : ?>
            					<? $mediaUrl = $this->url()->media($_Content_Avatar); ?>
								<img height="60" title="<?=$Content['title']?>" alt="" class="attachment-80x60" src="<?=$mediaUrl?>?h=60"/>
							<? else: ?>
								<img width="46" height="60" title="<?=$_Content_title?>" alt="" class="attachment-80x60" src="<?=$backUrl?>/images/files/default.png"/>
							<? endif; ?>
						</a>
					</td>
                    <td class="post-title page-title column-title">
						<?=$this->formHidden('content[id]', $_Content_id)?>
                        <strong><a class="row-title" href="<?=$contentOpenUrl?>" title="Open this">
                        	<?=$_Content_title?>
						</a></strong>
						<div class="row-actions">
							<span class="edit"><a title="Edit this" href="<?=$contentEditUrl?>">Edit</a> | </span>
							<span class="delete"><a class="delete-action"  title="Are you sure you want to delete <?=$_Content_title?>" href="<?=$contentDeleteUrl?>">Delete</a> | </span>
							<span class="view"><a rel="permalink" title="View" href="<?=$contentUrl?>">View</a></span>
						</div>
                    </td>
                    <td class="author column-author">
                        <?=delve($_Content,'description')?>
                    </td>
                    <td class="author column-author"><?
                        if ( !$_Content_Author ) :
                        	echo 'Unkown';
                        else:
                        	$author = delve($_Content_Author,'displayname');
                        	$author_url = $this->url(array(
                        		'action'=>'content-list',
                        		'search'=>$author
                        	), 'back', true);
                        	echo '<a href="'.$author_url.'" title="View all content by '.$author.'">'.$author.'</a>';
                    	endif;
                    ?></td>
                    <td class="author column-tags"> <?
                        if ( !$_Content_Tags ) :
                        	// nothing
                        else:
                        	$tags = array();
                        	foreach ( $_Content_Tags as $_Tag ) {
                        		$tag = ucfirst(delve($_Tag,'name'));
	                        	$tag_url = $this->url()->action('content-list')->search($tag)->param('type',$type);
	                        	$tags[] = '<a href="'.$tag_url.'" title="View all content by '.$tag.'">'.$tag.'</a>';
                        	}
                        	echo implode($tags, ', ');
                    	endif;
                    ?></td>
                    <!--<td class="comments column-comments">
                        <div class="post-com-count-wrapper">
                            <a href="http://localhost/wordpress/wp-back/edit-comments.php?p=2" title="0 pending" class="post-com-count"><span class="comment-count">0</span></a>
                        </div>
                    </td>-->
                    <td class="date column-date">
                        <abbr title="<?=$this->locale()->datetime($_Content_updated_at)?>">
                            <?=$this->locale()->timeago($_Content_updated_at)?>
                        </abbr>
                        <br/>
                        <?=delve($_Content,'status')?>
                    </td>
                </tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
	<? if ( $type === 'content' && !delve($this,'search.query') ) : // We only want to enable sorting on proper standard browsing ?>
    <script type="text/javascript">
    	$(function(){
			$content_list = $('#content-list');
			$content_list.sortable({
				update: function(event, ui) {
					var $this = $(this);
					var conpos = {};
					var $children = $this.children().each(function(i,v){
						var $content = $(this);
						var id = $content.find(':input.content-id').val();
						conpos[id] = i+1;
					});
					// Ajax Request
					var data = {json:JSON.stringify({positions:conpos})};
					$.ajax({
						url: "<?=$this->url()->action('content-position')?>",
						type: 'post',
						data: data,
						dataType: 'json',
						success: function(){
							$children.highlight();
						}
					});
				}
    		});
    	});
    </script>
	<? endif; ?>
</div>