<?
	# URLs
	$base_url_full = $this->app()->getBaseUrl(true);
	$back_url = $this->app()->getAreaUrl('back');
	$front_url = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	
	# Editor
	$editor = $this->app()->getConfig('bal.editor');
	
	# Content
	$Content = delve($this,'Content');
	$Content_Author = delve($Content,'Author');
	$Content_Avatar = delve($Content,'Avatar');
	$Content_Avatar_id = delve($Content_Avatar,'id');
	$Content_Avatar_title = delve($Content_Avatar,'title');
	$Content_Avatar_url = $this->url()->media($Content_Avatar)->toString();
	$Content_Parent = delve($Content,'Parent');
	$Content_Route = delve($Content,'Route');
	
	# Content URLs
	$Content_url = delve($Content,'id') ? $this->url()->content($Content)->toString() : '';
	
	# Crumbs
	$ContentCrumbs = delve($this,'ContentCrumbs',array($Content));
	$ContentList = delve($this,'ContentList');
	
	# Mode
	$mode = delve($Content,'id') ? 'edit' : 'new';
	$mode_edit = $mode === 'edit';
	
	# Type
	$type = delve($this,'type');
	$Type = ucfirst($type);
	
	# Title
	$this->headTitle()->append($Type);
	$this->headTitle()->append(delve($Content,'title','New'));
?>
<div class="wrap">
	<? if ( $type === 'event' ): ?>
		<div id="icon-themes" class="icon32"><br/></div>
	<? else: ?>
		<div id="icon-edit-pages" class="icon32"><br/></div>
	<? endif; ?>
	<h2>
		<?=$mode_edit?'Editing':'Create New '.$Type?>
		<? if ( $mode_edit ) foreach ( $ContentCrumbs as $_Content ): ?>
			&raquo; <a href="<?=$this->url()->action('content-list')->item($_Content)?>"><?=$this->app()->getItemLabel($_Content)?></a>
		<? endforeach; ?>
	</h2>
	<?=$this->log()->render()?>
	<form action="" method="post" enctype="multipart/form-data">
		<?=$this->formHidden('Content[type]', $type)?>
		<div class="metabox-holder has-right-sidebar">
			<div id="side-info-column" class="inner-sidebar">
				<div id='side-sortables' class='meta-box-sortables sidebar-boxes'>
				
					<div id="sidebar-publish-box" class="postbox sidebar-box sidebar-box-sections">
						<h3>Publish</h3>
						<div class="inside">
							<div id="minor-publishing">
								<div id="minor-publishing-actions">
									<?if($mode_edit):?>
										<!-- Open Action -->
										<a class="button button-action right" id="action-open" tabindex="4" href="<?=$Content_url?>" >Open</a>
									<?endif;?>
									<!-- Preview Action -->
									<!-- <a class="button button-action right" id="action-preview" tabindex="4">Preview</a>  -->
									<div class="clear"></div>
								</div>
								<div id="misc-publishing-actions">
									<div class="misc-pub-section field">
										<label for="content-status">Status:</label>
										<span id="content-status-view" class="field-value"><?=ucfirst(delve($Content,'status'))?></span>
										<span id="content-status-edit" class="hide">
											<br/>
											<?=$this->formDoctrine(array('target'=>array('Content','status'),'source'=>$this,'attribs'=>array('tabindex'=>50)))?>
										</span>
									</div>
									<? if ( $Content_Author ) :
			                        	$author = delve($Content_Author, 'displayname');
			                        	$author_url = $this->url()->action('content-list')->search($author)->toString();
			                        	$author_link = '<a href="'.$author_url.'" title="View all content by '.$author.'">'.$author.'</a>';
										?>
										<div class="misc-pub-section field" id="content-author-field">
											<label>Author:</label>
											<span class="field-value" id="content-author-view"><?=$author_link?></span>
										</div>
									<? endif; ?>
									<div class="misc-pub-section misc-pub-section-last field" id="content-published_at-field">
										<label for="content-published_at">Publish<?=$mode_edit?'<span class="weak">ed</span>':''?> on:</label>
										<span class="field-value" id="content-published_at-view"><?=$this->locale()->datetime(delve($Content,'published_at'))?></span>
										<span id="content-published_at-edit" class="hide">
											<br/>
											<?=$this->formDatetime('Content[published_at]', delve($Content,'published_at'), array('tabindex'=>55))?>
										</span>
									</div>
								</div>
								<div class="clear">
								</div>
							</div>
							<div id="major-publishing-actions">
								<!-- Delete Action -->
								<div id="delete-action">
									<a class="delete delete-action" id="action-delete" title="Are you sure you want to delete <?=delve($Content,'title')?>" href="<?=$this->url(array('action'=>'content-delete','content'=>delve($Content,'code')),'back',true)?>" ><?=$mode_edit?'Delete':'Discard'?></a>
								</div>
								<!-- Save Action -->
								<div id="publishing-action">
									<input name="save" type="submit" class="button-primary" id="action-save" tabindex="100" accesskey="p" value="Save" />
								</div>
								<div class="clear">
								</div>
							</div>
						</div>
					</div>
					
					<div id="sidebar-tags-box" class="postbox sidebar-box">
						<h3>Tags</h3>
						<div class="inside">
							<label class="screen-reader-text" for="content-tags">Post Tags</label>
							<?=$this->formTextarea('Content[tags][]',delve($Content,'tags'),array('tabindex'=>60, 'class'=>'form-input-tip autosize','title'=>'Add tags'))?>
							<p class="description">
								Add your tags to the post above, separating them with commas.
							</p>
						</div>
					</div>
					
					<div id="sidebar-avatar-box" class="postbox sidebar-box">
						<h3>Avatar</h3>
						<div class="inside">
            				<? if ( $Content_Avatar_id ) :
           						?>
								<div class="avatar">
									<a title="View <?=$Content_Avatar_url?>" href="<?=$Content_Avatar_url?>">
										<img height="60" title="<?=$Content_Avatar_title?>" alt="" class="attachment-80x60" src="<?=$Content_Avatar_url?>?h=60"/>
									</a>
								</div>
								<div class="avatar field">
									<?=$this->formCheckbox('Content[Avatar][_delete_]', 'true', array('tabindex'=>70))?>
									<label for="content-avatar-delete">
										Delete?
									</label>
								</div>
							<? endif; ?>
							<div class="field">
								<label for="content-avatar-file">
									Want to upload a different image?
								</label>
								<?=$this->formFile('Content[Avatar][file]', array('tabindex'=>75))?>
							</div>
						</div>
					</div>
					
					<div id="sidebar-subscription-box" class="postbox sidebar-box">
						<h3>Subscriptions</h3>
						<div class="inside">
							<? if ( delve($Content,'send_status') === 'none' ): ?>
								<div class="field">
									<?=$this->formCheckbox('Content[tags][]', 'newsletter', array('tabindex'=>80))?>
									<label for="subscription-tags">
										Send out as a
										<a href="<?=$this->url()->action('content-list')->search('newsletter')?>" title="Sent Content List">newsletter</a>
										to
										<a href="<?=$this->url()->action('subscriber-list')->search('newsletter')?>" title="Subscriber List">subscribers</a>?
									</label>
								</div>
							<? else: ?>
								<div class="field">
									<span class="label">Sent to:</span>
									<span class="value"><?=delve($Content,'send_all',0)-delve($Content,'send_remaining',0)?> of <?=delve($Content,'send_all',0)?> <a href="<?=$this->url(array('controller'=>'subscription','action'=>'subscriber-list'),'back',true)?>" title="go to Subscriber List">subscribers</a></span>
								</div>
							<? endif; ?>
						</div>
					</div>
					
				</div>
			</div>
			<div id="post-body">
				<div id="post-body-content" class="field-container">
					<div id="content-title-field" class="field field-simple">
						<label class="screen-reader-text" for="content-title">
							Title
						</label>
						<?=$this->formText('Content[title]', delve($Content,'title'), array('tabindex'=>10,'autocomplete'=>'off','class'=>'form-input-tip','title'=>'Title'))?>
					</div>
					<div id="content-parent-field" class="field field-little">
						<label for="content-parent">
							File under:
						</label>
						<select name="Content[Parent]" id="Content-parent" tabindex="20">
							<option <?=($Content_Parent ? 'selected="selected" ':'')?> value="0">- Top Level</option>
							<?
							$current = delve($Content_Parent,'id');
							$skip = $skip_factor = false;
							foreach( $ContentList as $_Content ):
								if ( $skip ) {
									if ( delve($_Content,'parent_id') <= $skip_factor ) {
										$skip = $skip_factor = false;
									} else {
										continue;
									}
								} elseif ( delve($_Content,'id') == delve($Content,'id') ) {
									$skip = true;
									$skip_factor = delve($_Content,'id');
									continue;
								}
								$option = array(
									'value' => delve($_Content,'id'),
									'title' => delve($_Content,'Route.path'),
									'label' => str_repeat('&nbsp;', ((int)delve($_Content,'level'))*2+2).'-&nbsp;'.delve($_Content,'title')
								);
								echo '<option '.($current==$option['value']?'selected="selected" ':'').' value="'.$option['value'].'" title="'.$option['title'].'">'.
									$option['label'].
								'</option>';
							endforeach;
							?>
						</select>
					</div>
					<div id="content-code-field" class="field field-little">
						<label for="content-code">
							Location:
						</label>
						<span class="inline-edit-clickable"><?=$base_url_full?>/</span><span id="content-parent-path" class="inline-edit-clickable"></span><span id="content-code-view" title="Click to edit this contents code" class="highlight"><?=delve($Content,'code')?></span><?=$this->formText('Content[code]', delve($Content,'code'))?>/
						<span class="inline-edit-panel" id="content-code-panel"></span>
					</div>
					
					<div id="content-content-field" class="field field-rich ">
						<? if ( $editor === 'bespin' ) : ?>
							<?=$this->formTextarea('Content[content]', '', array('tabindex'=>30, 'rows'=>5))?>
						<? else: ?>
							<?=$this->formTextarea('Content[content]', delve($Content,'content'), array('tabindex'=>30, 'rows'=>5))?>
						<? endif; ?>
					</div>
					
					<div id="content-description-field" class="field field-wrapper postbox widget">
						<h3>Excerpt</h3>
						<div class="inside">
							<?=$this->formTextarea('Content[description]', delve($Content,'description'), array('tabindex'=>40, 'rows'=>3))?>
						</div>
					</div>
					
					<? if ( $type === 'event' ): ?>
					<div id="content-description-field" class="field field-wrapper postbox widget">
						<h3>Event Information</h3>
						<div class="inside">
							<p>
								<label for="content-event-start-at">Start time:</label>
								<?=$this->formDatetime('Content[event_start_at]', delve($Content,'event_start_at',array('tabindex'=>45)))?>
							</p>
							<p>
								<label for="content-event-finish-at">Finish time:</label>
								<?=$this->formDatetime('Content[event_finish_at]', delve($Content,'event_finish_at',array('tabindex'=>46)))?>
							</p>
						</div>
					</div>
					<? endif; ?>
				</div>
			</div>
			<br class="clear" />
		</div>
		<!-- /poststuff -->
	</form>
</div>
<div class="clear">
</div>
<style type="text/css">
	#Content-content {
		width:100%;
		height:400px;
	}
</style>
<script type="text/javascript">
$(function(){
	$("#content-status-view").inlineEdit({
		edit: "#content-status-edit"
	});
	//
	//$("#content-published_at-view").inlineEdit({
	//	edit: "#content-published_at-edit"
	//});
	//
	$('#sidebar-tags-box h3').help('Tags are the keywords used to find your content during a search.');
	$('#sidebar-avatar-box h3').help('Avatars display side by side your content. They are a nice visual addition and will be uploaded to your media directory.');
	$('#sidebar-subscription-box h3').help('Subscribers are visitors of the website which have marked themselves down to receive email notifications from the website.');
	//
	var update_slug = true;
	var $edit = $('#Content-code');
	var $view = $('#content-code-view');
	var $title = $('#Content-title');
	var $parent_path = $('#content-parent-path');
	var $parent = $('#Content-parent');
	$parent.change(function(){
		$parent_path.text($parent.val().toInt() ? $parent.find('option:selected').attr('title').strip('\\/')+'/' : '');
		return true;
	}).trigger('change');
	$view.inlineEdit('editbutton', {
		edit: $edit,
		panel: '#content-code-panel',
		update: function(e,els,config) {
			update_slug = false;
			els.$view.html(els.$edit.value().toSlug());
			els.$views.show();
			els.$edits.hide();
			return true;
		}
	});
	if ( update_slug && (!$edit.val() || $edit.val() === $title.text().toSlug()) ) {
		// We are not already a custom slug
		$title.change(function(){
			if ( !update_slug ) return true;
			var val = $(this).val();
			var slug = val.toSlug();
			$edit.val(slug);
			$view.text(slug);
			return true;
		});
	}
	// Help
	$('#content-description-field h3').help('Excerpts are hand-crafted summaries of your content, they are used within such things as listings and search results.');
	// Editors
	<? if ( $editor === 'tinymce' ) : ?>
		$('#Content-content').Tinymce('rich');
		$('#Content-description').Tinymce('simple');
	<? elseif ( $editor === 'bespin' ): ?>
		$('#Content-content').Bespin('rich', {content:"<?=format_to_output(delve($Content,'content',''),'jsattr')?>"});
		//$('#Content-description').Bespin('simple');
	<? endif; ?>
});
</script>