<?
	// URLs
	$publicUrl = $this->app()->getPublicUrl();
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	// Type
	$type = $this->type;
	$Type = ucfirst($type);
	// Title
	$this->headTitle()->append($Type);
?><div class="wrap">
	<!-- Edit Button -->
    <div id="icon-edit-pages" class="icon32">
        <br/>
    </div>
	<!-- Header -->
    <h2>
		<a href="<?=$this->url(array('action'=>'content-list'),'back',true)?>"><?=$Type?> List</a>
		<? foreach ( $this->ContentCrumbArray as $Content ): ?>
			&raquo; <a href="<?=$this->url(array('action'=>'content-list','content'=>$Content['code']),'back')?>"><?=$Content['title']?></a>
		<? endforeach; ?>
	</h2>
    <!-- Filters -->
    <form id="posts-filter" action="<?=$this->url(array('action'=>'content-list'),'back',true)?>" method="get">
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="page-search-input">
                Search:
            </label>
            <input id="page-search-input" name="search" type="text" />
            <input value="Search" class="button" type="submit" />
        </p>
        <div class="clear">
        </div>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon" />
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        Title
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Description
                    </th>
                    <th scope="col" id="author" class="manage-column column-author" style="">
                        Author
                    </th>
                    <th scope="col" id="author" class="manage-column column-tags" style="">
                        Tags
                    </th>
					<!--<th scope="col" id="comments" class="manage-column column-comments num" style="">
                        <div class="vers">
                            <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                        </div>
                    </th>-->
                    <th scope="col" id="date" class="manage-column column-date" style="">
                        Date
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon" />
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        Title
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Description
                    </th>
                    <th scope="col" id="author" class="manage-column column-author" style="">
                        Author
                    </th>
                    <th scope="col" id="author" class="manage-column column-tags" style="">
                        Tags
                    </th>
					<!--<th scope="col" id="comments" class="manage-column column-comments num" style="">
                        <div class="vers">
                            <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                        </div>
                    </th>-->
                    <th scope="col" id="date" class="manage-column column-date" style="">
                        Date
                    </th>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="content-list">
            	<? foreach ( $this->ContentListArray as $Content ): ?>
            	<?
            		$contentUrl = $this->content()->getContentUrl($Content);
            		$contentOpenUrl = $this->url(array('action'=>'content-list','content'=>$Content['code']),'back',true);
            		$contentEditUrl = $this->url(array('action'=>'content-edit','content'=>$Content['code']),'back',true);
            	?>
                <tr id="content-<?=$Content['id']?>" class="<?=$this->cycle(array('alternate',''), 'ContentTreeArray')->next()?>">
                	<td class="column-icon media-icon">
						<a title="View <?=$Content['title']?>" href="<?=$contentUrl?>">
							<? if ( !empty($Content['Avatar']) && $Content['Avatar']['type'] === 'image' ) : ?>
            					<? $mediaUrl = $this->content()->getMediaUrl($Content['Avatar']); ?>
								<img height="60" title="<?=$Content['title']?>" alt="" class="attachment-80x60" src="<?=$mediaUrl?>?h=60"/>
							<? else: ?>
								<img width="46" height="60" title="<?=$Content['title']?>" alt="" class="attachment-80x60" src="<?=$backUrl?>/images/files/default.png"/>
							<? endif; ?>
						</a>
					</td>
                    <td class="post-title page-title column-title">
                    	<input type="hidden" name="content[id]" class="content-id" value="<?=$Content['id']?>" />
                        <strong><a class="row-title" href="<?=$contentOpenUrl?>" title="Open this">
                        	<?=/*str_repeat('&nbsp;',$Content['level']).' '.*/$Content['title']?>
						</a></strong>
						<div class="row-actions">
							<span class="edit"><a title="Edit this" href="<?=$contentEditUrl?>">Edit</a> | </span>
							<span class="delete"><a class="delete-action"  title="Are you sure you want to delete <?=$Content['title']?>" href="<?=$this->url(array('action'=>'content-delete','content'=>$Content['code']),'back',true)?>">Delete</a> | </span>
							<span class="view"><a rel="permalink" title="View" href="<?=$contentUrl?>">View</a></span>
						</div>
                    </td>
                    <td class="author column-author">
                        <?=$Content['description']?>
                    </td>
                    <td class="author column-author"><?
                        if ( empty($Content['Author']) ) :
                        	echo 'Unkown';
                        else:
                        	$author = $Content['Author']['displayname'];
                        	$author_url = $this->url(array(
                        		'action'=>'content-list',
                        		'search'=>$author
                        	), 'back', true);
                        	echo '<a href="'.$author_url.'" title="View all content by '.$author.'">'.$author.'</a>';
                    	endif;
                    ?></td>
                    <td class="author column-tags"> <?
                        if ( empty($Content['Tags']) ) :
                        	// nothing
                        else:
                        	$tags = array();
                        	foreach ( $Content['Tags'] as $Tag ) {
                        		$tag = ucfirst($Tag['name']);
	                        	$tag_url = $this->url(array(
	                        		
	                        		'action'=>'content-list',
	                        		'search'=>$tag
	                        	), 'back', true);
	                        	$tags[] = '<a href="'.$tag_url.'" title="View all content by '.$tag.'">'.$tag.'</a>';
                        	}
                        	echo implode($tags, ', ');
                    	endif;
                    ?></td>
                    <!--<td class="comments column-comments">
                        <div class="post-com-count-wrapper">
                            <a href="http://localhost/wordpress/wp-back/edit-comments.php?p=2" title="0 pending" class="post-com-count"><span class="comment-count">0</span></a>
                        </div>
                    </td>-->
                    <td class="date column-date">
                        <abbr title="<?=$this->locale()->datetime($Content['updated_at'])?>">
                            <?=$this->locale()->timeago($Content['updated_at'])?>
                        </abbr>
                        <br/>
                        <?=$Content['status']?>
                    </td>
                </tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
    <script type="text/javascript">
    	$(function(){
			$content_list = $('#content-list');
			$content_list.sortable({
				update: function(event, ui) {
					var $this = $(this);
					var conpos = {};
					var $children = $this.children().each(function(i,v){
						var $content = $(this);
						var id = $content.find(':input.content-id').val();
						conpos[id] = i+1;
					});
					// Ajax Request
					var data = {json:JSON.stringify({positions:conpos})};
					$.ajax({
						url: '<?=$this->url(array('action'=>'content-position'),'back',true)?>',
						type: 'post',
						data: data,
						dataType: 'json',
						success: function(){
							$children.highlight();
						}
					});
				}
    		});
    	});
    </script>
</div>