<?
	# Prepare
	$this->url()->renege('route','front');
	$base_url = $this->app()->getBaseUrl();
	# Extract
	$Article = delve($this,'Article');
	$Article_code = delve($Article,'code');
	$Article_title = delve($Article,'title');
	$Article_tagline = delve($Article,'tagline');
	$Article_Avatar = delve($Article,'Avatar');
	# Url
	$Article_url = $this->url()->content($Article)->toString();
	# Crumbs
	$ArticleCrumbs = delve($this,'ArticleCrumbs');
	# Class
	if ( empty($class) ) $class = array();
	elseif ( !is_array($clasS) ) $class = array($class);
	$class = implode(' ',$class);
?>
<article id="article" class="article">
	<div id="article-<?=$Article_code?>" class="article <?=$class?>">
	
		<header class="article-header">
			<nav id="nav-crumbs">
				<ul>
					<li>
						<a href="<?=$base_url?>">
							<span class="title">Home</span>
						</a>
					</li>
					<li>
						<span class="separator">/</span>
					</li>
					<? foreach ( $ArticleCrumbs as $Crumb ) :
						$Crumb_title = delve($Crumb,'title');
						$Crumb_url = $this->url()->content($Crumb)->toString();
						?>
						<li>
							<a href="<?=$Crumb_url?>">
								<span class="title"><?=$Crumb_title?></span>
							</a>
						</li>
						<li>
							<span class="separator">/</span>
						</li>
					<? endforeach; ?>
				</ul>
			</nav>
			<div class="article-title">
				<h1>
					<a href="<?=$Article_url?>" title="<?=$Article_title?>">
						<span class="title"><?=$Article_title?></span>
						<span class="description"><?=$Article_tagline?></span>
					</a>
				</h1>
			</div>
		</header>
	
		<? if ( $Article_Avatar ) :
			$Media = $Article_Avatar;
			$Media_url = $this->url()->media($Media)->toString();
			?>
			<div class="article-avatar">
				<a href="<?=$Media_url?>" title="View Image">
					<img src="<?=$Media_url?>?width=200" title="<?=$Article_title?>" alt="<?=$Article_title?> Avatar" />
				</a>
			</div>
		<? endif; ?>

		<div class="article-content">
			<?=$this->article()->renderArticle($Article)?>
		</div>
	
	</div>
</article>