<?
	$Content = $this->Content;
	$contentUrl = $this->content()->getContentUrl($Content);
?>
<div id="content-<?=$Content->code?>" class="content">
	<div id="content-header" class="content-header">
		<h2>
			<a href="<?=$contentUrl?>" title="<?=$Content->title?>">
				<?=$Content->title?>
			</a>
		</h2>
	</div>
	
	<? if ( count($Content->Avatar) && $Content->Avatar->exists() ) :
		$Media = $Content->Avatar;
		$mediaUrl = $this->content()->getMediaUrl($Content);
		?>
		<div id="content-avatar" class="content-avatar">
			<a href="<?=$mediaUrl?>" title="View Image">
				<img src="<?=$mediaUrl?>?width=200" title="<?=$Content->title?>" alt="<?=$Content->title?> Avatar" />
			</a>
		</div>
	<? endif; ?>
	<div id="content-content" class="content-content">
		<?=$this->content()->renderContent($Content)?>
	</div>
</div>