<?
	//
	$Content = delve($this,'Content');
	$Content_title = delve($Content,'title');
	$Content_Avatar = delve($Content,'Avatar');
	//
	$contentUrl = $this->content()->getContentUrl($Content);
?>
<div id="content-<?=$Content->code?>" class="content">
	<div id="content-header" class="content-header">
		<h2>
			<a href="<?=$contentUrl?>" title="<?=$Content_title?>">
				<?=$Content_title?>
			</a>
		</h2>
	</div>
	
	<? if ( $Content_Avatar ) :
		$Media = $Content_Avatar;
		$mediaUrl = $this->content()->getMediaUrl($Content);
		?>
		<div id="content-avatar" class="content-avatar">
			<a href="<?=$mediaUrl?>" title="View Image">
				<img src="<?=$mediaUrl?>?width=200" title="<?=$Content_title?>" alt="<?=$Content_title?> Avatar" />
			</a>
		</div>
	<? endif; ?>
	<div id="content-content" class="content-content">
		<?=$this->content()->renderContent($Content)?>
	</div>
</div>