<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$search = delve($this,'search');
	$ContentList = delve($this,'ContentList');
?>
<div id="content-search" class="content">
	<h2>
		Search: <?=delve($search,'query')?>
	</h2>
	<div id="content-content" class="content-content">
	
		<div class="contentlist">
			<? foreach ( $ContentList as $Content ) :
				$Content_title = delve($Content,'title');
				?>
				<div class="contentlist-content">
					<h3><a href="<?=$this->url()->content($Content)?>" title="<?=$Content_title?>"><?=$Content_title?></a></h3>
					<div class="contentlist-content-content">
						<?=$this->content()->renderDescription($Content)?>
					</div>
				</div>
			<? endforeach; ?>
		</div>
		
	</div>
</div>