<?
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlBack = $this->bal()->getBaseUrl('back');
	$mode = empty($this->ContentArray) || empty($this->ContentArray['id']) ? 'new' : 'edit';
	$mode_edit = $mode === 'edit';
	$type = $this->type;
	$Type = ucfirst($type);
	$this->headTitle()->append($Type);
	$this->headTitle()->append(empty($this->ContentArray['title'])?'New':$this->ContentArray['title']);
?>
<div class="wrap">
	<? if ( $type === 'event' ): ?>
		<div id="icon-themes" class="icon32"><br/></div>
	<? else: ?>
		<div id="icon-edit-pages" class="icon32"><br/></div>
	<? endif; ?>
	<h2>
		<?=$mode_edit?'Editing':'Create New '.$Type?>
		<? if ( $mode_edit ) foreach ( $this->ContentCrumbArray as $Content ): ?>
			&raquo; <a href="<?=$this->url(array('action'=>'content-list','content'=>$Content['code']),'admin')?>"><?=$Content['title']?></a>
		<? endforeach; ?>
	</h2>
	<?=$this->message()->render()?>
	<form action="" method="post" enctype="multipart/form-data">
		<input type="hidden" name="content[type]" value="<?=$type?>" />
		<div class="metabox-holder has-right-sidebar">
			<div id="side-info-column" class="inner-sidebar">
				<div id='side-sortables' class='meta-box-sortables sidebar-boxes'>
				
					<div id="sidebar-publish-box" class="postbox sidebar-box sidebar-box-sections">
						<h3>Publish</h3>
						<div class="inside">
							<div id="minor-publishing">
								<div id="minor-publishing-actions">
									<?if($mode_edit):?>
									<!-- Open Action -->
									<a class="button button-action right" id="action-open" tabindex="4" href="<?=$this->url(array('Map'=>$this->ContentArray['Route']),'map',true)?>" >Open</a>
									<?endif;?>
									<!-- Preview Action -->
									<!-- <a class="button button-action right" id="action-preview" tabindex="4">Preview</a>  -->
									<div class="clear"></div>
								</div>
								<div id="misc-publishing-actions">
									<div class="misc-pub-section field">
										<label for="content-status">Status:</label>
										<span id="content-status-view" class="field-value"><?=ucfirst($this->ContentArray['status'])?></span>
										<span id="content-status-edit" class="hide">
											<br/>
											<select name="content[status]" id="content-status" tabindex="4">
												<? foreach ( Doctrine::getTable('Content')->getEnumValues('status') as $value ):
													echo '<option '.($this->ContentArray['status']==$value?'selected="selected" ':'').' value="'.$value.'">'.ucfirst($value).'</option>';
												endforeach; ?>
											</select>
										</span>
										<script type="text/javascript">
											$("#content-status-view").inlineEdit({
												edit: "#content-status-edit"
											});
										</script>
									</div>
									<div class="misc-pub-section misc-pub-section-last field" id="content-published_at-field">
										<label for="content-published_at">Publish<?=$mode_edit?'<span class="weak">ed</span>':''?> on:</label>
										<span class="field-value" id="content-published_at-view"><?=$this->locale()->datetime($this->ContentArray['published_at'])?></span>
										<span id="content-published_at-edit" class="hide">
											<br/>
											<input type="text" name="content[published_at]" id="content-published_at" value="<?=$this->ContentArray['published_at']?>" class="sparkle-datetime"></input>
										</span>
										<script type="text/javascript">
											//$("#content-published_at-view").inlineEdit({
											//	edit: "#content-published_at-edit"
											//});
										</script>
									</div>
								</div>
								<div class="clear">
								</div>
							</div>
							<div id="major-publishing-actions">
								<!-- Delete Action -->
								<div id="delete-action">
									<a class="delete delete-action" id="action-delete" title="Are you sure you want to delete <?=$this->ContentArray['title']?>" href="<?=$this->url(array('action'=>'content-delete','content'=>$this->ContentArray['code']),'admin',true)?>" ><?=$mode_edit?'Delete':'Discard'?></a>
								</div>
								<!-- Save ACtion -->
								<div id="publishing-action">
									<input name="save" type="submit" class="button-primary" id="action-save" tabindex="5" accesskey="p" value="Save" />
								</div>
								<div class="clear">
								</div>
							</div>
						</div>
					</div>
					
					<div id="sidebar-tags-box" class="postbox sidebar-box">
						<h3>Tags</h3>
						<div class="inside">
							<label class="screen-reader-text" for="content-tags">Post Tags</label>
							<textarea id="content-tags" name="content[tags]" class="form-input-tip autosize" title="Add tags"><?=$this->ContentArray['tagstr']?></textarea>
							<p class="description">
								Add your tags to the post above, separating them with commas.
							</p>
						</div>
						<script type="text/javascript">
							$('#sidebar-tags-box h3').help('Tags are the keywords used to find your content during a search.');
						</script>
					</div>
					
					<div id="sidebar-avatar-box" class="postbox sidebar-box">
						<h3>Avatar</h3>
						<div class="inside">
							<div class="field">
            					<? if ( !empty($Content['Avatar']) && !empty($Content['Avatar']['id']) ) :
            						$Media = $Content['Avatar'];
            						$mediaUrl = $baseUrl.$Media['url'];
            						?>
									<p style="text-align:center;">
										<a title="View <?=$Media['title']?>" href="<?=$mediaUrl?>">
											<img height="60" title="<?=$Media['title']?>" alt="" class="attachment-80x60" src="<?=$mediaUrl?>?w=59"/>
										</a>
									</p>
								<? endif; ?>
								<label for="content-avatar">
									Want to upload a different image?
								</label>
								<input type="file" id="content-avatar"  name="avatar"" />
							</div>
						</div>
						<script type="text/javascript">
							$('#sidebar-avatar-box h3').help('Avatars display side by side your content. They are a nice visual addition and will be uploaded to your media directory.');
						</script>
					</div>
					
					<div id="sidebar-subscription-box" class="postbox sidebar-box">
						<h3>Subscriptions</h3>
						<div class="inside">
							<? if ( $this->ContentArray['send_status'] === 'none' ): ?>
								<div class="field">
									<input type="checkbox" id="subscription-tags" name="subscription[tags]" value="newsletter" />
									<label for="subscription-tags">
										Send out as a
										<a href="<?=$this->url(array('controller'=>'subscription','action'=>'content-list'),'admin',true)?>" title="go to Sent Content List">newsletter</a>
										to
										<a href="<?=$this->url(array('controller'=>'subscription','action'=>'subscriber-list'),'admin',true)?>" title="go to Subscriber List">subscribers</a>?
									</label>
								</div>
							<? else: ?>
								<div class="field">
									<span class="label">Sent to:</span>
									<span class="value"><?=$this->ContentArray['send_all']-$this->ContentArray['send_remaining']?> of <?=$this->ContentArray['send_all']?> <a href="<?=$this->url(array('controller'=>'subscription','action'=>'subscriber-list'),'admin',true)?>" title="go to Subscriber List">subscribers</a></span>
								</div>
							<? endif; ?>
						</div>
						<script type="text/javascript">
							$('#sidebar-subscription-box h3').help('Subscribers are visitors of the website which have marked themselves down to receive email notificationsom from the website.');
						</script>
					</div>
					
				</div>
			</div>
			<div id="post-body">
				<div id="post-body-content" class="field-container">
					<div id="content-title-field" class="field field-simple">
						<label class="screen-reader-text" for="content-title">
							Title
						</label>
						<input type="text" name="content[title]" id="content-title" tabindex="1" value="<?=$this->ContentArray['title']?>" autocomplete="off" />
					</div>
					<div id="content-parent-field" class="field field-little">
						<label for="content-parent">
							File under:
						</label>
						<select name="content[parent]" id="content-parent">
							<option <?=($this->ContentArray['Parent']['id']==0?'selected="selected" ':'')?> value="0">- Top Level</option>
							<?
							$skip = $skip_factor = false;
							foreach($this->ContentListArray as $Content ):
								if ( $skip ) {
									if ( $Content['parent_id'] <= $skip_factor ) {
										$skip = $skip_factor = false;
									} else {
										continue;
									}
								} elseif ( $Content['id'] == $this->ContentArray['id'] ) {
									$skip = true;
									$skip_factor = $Content['id'];
									continue;
								}
								echo '<option '.($this->ContentArray['Parent']['id']==$Content['id']?'selected="selected" ':'').' value="'.$Content['id'].'" title="'.$Content['Route']['path'].'">'.
									str_repeat('&nbsp;', ((int)$Content['level'])*2+2).'-&nbsp;'.$Content['title'].
								'</option';
							endforeach; ?>
						</select>
					</div>
					<div id="content-code-field" class="field field-little">
						<label for="content-code">
							Location:
						</label>
						<span class="inline-edit-clickable"><?=$this->bal()->getBaseUrl('front',true)?>/</span><span id="content-parent-path" class="inline-edit-clickable"></span><span id="content-code-view" title="Click to edit this contents code" class="highlight"><?=$this->ContentArray['code']?></span><input type="text" name="content[code]" id="content-code" value="<?=$this->ContentArray['code']?>" />/
						<span class="inline-edit-panel" id="content-code-panel"></span>
					</div>
					<script type="text/javascript">
						$(function(){
							var update_slug = true;
							var $edit = $('#content-code');
							var $view = $('#content-code-view');
							var $title = $('#content-title');
							var $parent_path = $('#content-parent-path');
							var $parent = $('#content-parent');
							$parent.change(function(){
								$parent_path.text($parent.val().toInt() ? $parent.find('option:selected').attr('title').strip('/')+'/' : '');
								return true;
							}).trigger('change');
							$view.inlineEdit('editbutton', {
								edit: $edit,
								panel: '#content-code-panel',
								update: function(e,els,config) {
									update_slug = false;
									els.$view.html(els.$edit.value().toSlug());
									els.$views.show();
									els.$edits.hide();
									return true;
								}
							});
							if ( update_slug && (!$edit.val() || $edit.val() === $title.text().toSlug()) ) {
								// We are not already a custom slug
								$title.change(function(){
									if ( !update_slug ) return true;
									var val = $(this).val();
									var slug = val.toSlug();
									$edit.val(slug);
									$view.text(slug);
									return true;
								});
							}
						});
					</script>
					
					<div id="content-content-field" class="field field-rich ">
						<? if ( $type === 'event' ): ?>
							<textarea name="content[content]" tabindex="2" id="content-content">[event/]</textarea>
							<script type="text/javascript">$(function(){$('#content-content-field').hide();});</script>
						<? else: ?>
							<textarea name="content[content]" tabindex="2" id="content-content"><?=$this->ContentArray['content']?></textarea>
							<script type="text/javascript">$(function(){$('#content-content').editor('rich');});</script>
						<? endif; ?>
					</div>
					
					<? if ( $type === 'event' ): ?>
					<div id="content-event-content-field" class="field field-rich ">
						<textarea name="content[event_content]" tabindex="3" id="content-event-content"><?=$this->ContentArray['event_content']?></textarea>
						<script type="text/javascript">$(function(){$('#content-event-content').editor('rich');});</script>
					</div>
					<? endif; ?>
					
					<div id="content-description-field" class="field field-wrapper postbox widget">
						<h3>Excerpt</h3>
						<div class="inside">
							<textarea rows="3" cols="40" name="content[description]" tabindex="4" id="content-description"><?=$this->ContentArray['description']?></textarea>
						</div>
						<script type="text/javascript">
							$('#content-description-field h3').help('Excerpts are hand-crafted summaries of your content, they are used within such things as listings and search results.');
							$('#content-description').editor('simple');
						</script>
					</div>
					
					<? if ( $type === 'event' ): ?>
					<div id="content-description-field" class="field field-wrapper postbox widget">
						<h3>Event Information</h3>
						<div class="inside">
							<p>
								<label for="content-event-start-at">Start time:</label>
								<input type="text" class="jquery-datetime" name="content[event_start_at]" id="content-event-start-at" value="<?=$this->ContentArray['event_start_at']?>" />
							</p>
							<p>
								<label for="content-event-finish-at">Finish time:</label>
								<input type="text" class="jquery-datetime" name="content[event_finish_at]" id="content-event-finish-at" value="<?=$this->ContentArray['event_finish_at']?>" />
							</p>
						</div>
					</div>
					<? endif; ?>
				</div>
			</div>
			<br class="clear" />
		</div>
		<!-- /poststuff -->
	</form>
</div>
<div class="clear">
</div>