<?php

/**
 * Base_Bal_Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $template
 * @property decimal $cost
 * @property decimal $subtotal
 * @property decimal $tax
 * @property array $config
 * @property array $cache
 * @property integer $for_id
 * @property integer $by_id
 * @property User $For
 * @property User $By
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Bal_Invoice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__invoice');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '50',
             ));
        $this->hasColumn('template', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'default' => 'user_invoice',
             'extra' => 
             array(
              'auto' => true,
             ),
             'length' => '50',
             ));
        $this->hasColumn('cost', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'extra' => 
             array(
              'currency' => true,
             ),
             'length' => '8',
             ));
        $this->hasColumn('subtotal', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'extra' => 
             array(
              'currency' => true,
             ),
             'length' => '8',
             ));
        $this->hasColumn('tax', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 2,
             'notnull' => true,
             'extra' => 
             array(
              'currency' => true,
             ),
             'length' => '8',
             ));
        $this->hasColumn('config', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
        $this->hasColumn('cache', 'array', null, array(
             'type' => 'array',
             'notnull' => true,
             ));
        $this->hasColumn('for_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('by_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as For', array(
             'local' => 'for_id',
             'foreign' => 'id'));

        $this->hasOne('User as By', array(
             'local' => 'by_id',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
    }
}