<?php

/**
 * Base_Bal_InvoiceItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property decimal $cost
 * @property string $template
 * @property integer $invoice_id
 * @property Invoice $Invoice
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Bal_InvoiceItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__invoice_item');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '50',
             ));
        $this->hasColumn('cost', 'decimal', 8, array(
             'type' => 'decimal',
             'scale' => 2,
             'notblank' => true,
             'extra' => 
             array(
              'currency' => true,
             ),
             'length' => '8',
             ));
        $this->hasColumn('template', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'default' => 'user_invoiceitem',
             'extra' => 
             array(
              'auto' => true,
             ),
             'length' => '50',
             ));
        $this->hasColumn('invoice_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'notblank' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Invoice', array(
             'local' => 'invoice_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}