<?php

/**
 * Base_Bal_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $send_on
 * @property timestamp $sent_on
 * @property string $title
 * @property string $description
 * @property boolean $unread
 * @property string $hash
 * @property enum $status
 * @property string $template
 * @property integer $for_id
 * @property integer $by_id
 * @property integer $content_id
 * @property User $For
 * @property User $By
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Bal_Message extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__message');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '3',
             ));
        $this->hasColumn('send_on', 'timestamp', null, array(
             'type' => 'timestamp',
             'notblank' => true,
             ));
        $this->hasColumn('sent_on', 'timestamp', null, array(
             'type' => 'timestamp',
             'extra' => 
             array(
              'auto' => true,
             ),
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             'extra' => 
             array(
              'html' => true,
             ),
             ));
        $this->hasColumn('unread', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             'extra' => 
             array(
              'auto' => true,
             ),
             ));
        $this->hasColumn('hash', 'string', 33, array(
             'type' => 'string',
             'unique' => true,
             'notblank' => true,
             'extra' => 
             array(
              'auto' => true,
             ),
             'length' => '33',
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'notblank' => true,
             'values' => 
             array(
              0 => 'pending',
              1 => 'published',
             ),
             'default' => 'pending',
             'extra' => 
             array(
              'auto' => true,
             ),
             ));
        $this->hasColumn('template', 'string', 30, array(
             'type' => 'string',
             'notblank' => true,
             'default' => 'user_message',
             'extra' => 
             array(
              'auto' => true,
             ),
             'length' => '30',
             ));
        $this->hasColumn('for_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('by_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('content_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as For', array(
             'local' => 'for_id',
             'foreign' => 'id'));

        $this->hasOne('User as By', array(
             'local' => 'by_id',
             'foreign' => 'id'));
    }
}