<?php

/**
 * Base_Bal_PermissionAndUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $assigned_date
 * @property integer $UserFrom_id
 * @property integer $User_id
 * @property integer $Permission_id
 * @property User $UserFrom
 * @property User $User
 * @property Permission $Permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Bal_PermissionAndUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__permission_and_user');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '3',
             ));
        $this->hasColumn('assigned_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('UserFrom_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('User_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('Permission_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as UserFrom', array(
             'local' => 'UserFrom_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('User', array(
             'local' => 'User_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Permission', array(
             'local' => 'Permission_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}