<?php

/**
 * Base_Bal_PermissionAndUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $assigned_date
 * @property integer $assignee_user_id
 * @property integer $user_id
 * @property integer $permission_id
 * @property User $Assignee
 * @property User $User
 * @property Permission $Permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Bal_PermissionAndUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__permission_and_user');
        $this->hasColumn('id', 'integer', 3, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '3',
             ));
        $this->hasColumn('assigned_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('assignee_user_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => false,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('user_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('permission_id', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as Assignee', array(
             'local' => 'assignee_user_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Permission', array(
             'local' => 'permission_id',
             'foreign' => 'id'));
    }
}