<?php

/**
 * Base_Bal_Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Bal_Permission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__permission');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}