<?php

/**
 * Base_Bal_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property integer $level
 * @property Doctrine_Collection $Permissions
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Bal_Role extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__role');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('code', 'string', 15, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '15',
             ));
        $this->hasColumn('level', 'integer', 1, array(
             'type' => 'integer',
             'notblank' => true,
             'unsigned' => true,
             'default' => 1,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permission as Permissions', array(
             'refClass' => 'PermissionAndRole',
             'local' => 'Role_id',
             'foreign' => 'Permission_id',
             'onDelete' => 'NO ACTION'));
    }
}