<?php

/**
 * Base_Bal_Route
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $path
 * @property string $type
 * @property array $data
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Bal_Route extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('bal__route');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('path', 'string', 150, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '150',
             ));
        $this->hasColumn('type', 'string', 15, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '15',
             ));
        $this->hasColumn('data', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'path',
             ),
             ));
        $this->actAs($softdelete0);
        $this->actAs($searchable0);
    }
}