<?php

/**
 * Base_Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Children
 * @property Doctrine_Collection $Messages
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Content extends Balcms_Content
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Balcms_Content as Children', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('Balcms_Message as Messages', array(
             'local' => 'id',
             'foreign' => 'content_id'));
    }
}