<?php

/**
 * Base_Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $InvoiceItems
 * @property Doctrine_Collection $InvoiceDataBackup
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Invoice extends Bal_Invoice
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_InvoiceItem as InvoiceItems', array(
             'local' => 'id',
             'foreign' => 'Invoice_id'));

        $this->hasMany('InvoiceDataBackup', array(
             'local' => 'id',
             'foreign' => 'Invoice_id'));
    }
}