<?php

/**
 * Base_Invoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $InvoiceItems
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Invoice extends Bal_Invoice
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_InvoiceItem as InvoiceItems', array(
             'local' => 'id',
             'foreign' => 'invoice_id'));
    }
}