<?php

/**
 * Base_Media
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property string $title
 * @property string $extension
 * @property string $path
 * @property integer $size
 * @property enum $type
 * @property string $mimetype
 * @property string $humantype
 * @property integer $width
 * @property integer $height
 * @property Doctrine_Collection $ContentList
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Media extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('media');
        $this->hasColumn('id', 'integer', 2, array(
             'primary' => true,
             'type' => 'integer',
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('extension', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '3',
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('size', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'file',
              1 => 'document',
              2 => 'image',
              3 => 'video',
              4 => 'audio',
              5 => 'web',
              6 => 'application',
              7 => 'archive',
             ),
             'default' => 'unknown',
             'notnull' => true,
             ));
        $this->hasColumn('mimetype', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('humantype', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('width', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('height', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Content as ContentList', array(
             'local' => 'id',
             'foreign' => 'avatar_id'));

        $bal_doctrine_template_auditable0 = new Bal_Doctrine_Template_Auditable(array(
             'status' => 
             array(
              'disabled' => true,
             ),
             'enabled' => 
             array(
              'disabled' => true,
             ),
             'author' => 
             array(
              'disabled' => false,
             ),
             'authorstr' => 
             array(
              'disabled' => true,
             ),
             'created_at' => 
             array(
              'disabled' => false,
             ),
             'updated_at' => 
             array(
              'disabled' => false,
             ),
             'published_at' => 
             array(
              'disabled' => true,
             ),
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'code',
              1 => 'title',
              2 => 'path',
              3 => 'type',
             ),
             ));
        $this->actAs($bal_doctrine_template_auditable0);
        $this->actAs($searchable0);
    }
}