<?php

/**
 * Base_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $MessagesChild
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Message extends Balcms_Message
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_Message as MessagesChild', array(
             'local' => 'id',
             'foreign' => 'MessageParent_id'));
    }
}