<?php

/**
 * Base_Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Roles
 * @property Doctrine_Collection $Bal_PermissionAndRole
 * @property Doctrine_Collection $Bal_PermissionAndUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Permission extends Bal_Permission
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_User as Users', array(
             'refClass' => 'PermissionAndUser',
             'local' => 'Permission_id',
             'foreign' => 'User_id'));

        $this->hasMany('Bal_Role as Roles', array(
             'refClass' => 'PermissionAndRole',
             'local' => 'Permission_id',
             'foreign' => 'Role_id'));

        $this->hasMany('Bal_PermissionAndRole', array(
             'local' => 'id',
             'foreign' => 'Permission_id'));

        $this->hasMany('Bal_PermissionAndUser', array(
             'local' => 'id',
             'foreign' => 'Permission_id'));
    }
}