<?php

/**
 * Base_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Bal_PermissionAndRole
 * @property Doctrine_Collection $Bal_RoleAndUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Role extends Bal_Role
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_User as Users', array(
             'refClass' => 'RoleAndUser',
             'local' => 'role_id',
             'foreign' => 'user_id'));

        $this->hasMany('Bal_PermissionAndRole', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $this->hasMany('Bal_RoleAndUser', array(
             'local' => 'id',
             'foreign' => 'role_id'));
    }
}