<?php

/**
 * Base_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $Bal_PermissionAndRole
 * @property Doctrine_Collection $Bal_RoleAndUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Role extends Bal_Role
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_User as Users', array(
             'refClass' => 'RoleAndUser',
             'local' => 'Role_id',
             'foreign' => 'User_id'));

        $this->hasMany('Bal_PermissionAndRole', array(
             'local' => 'id',
             'foreign' => 'Role_id'));

        $this->hasMany('Bal_RoleAndUser', array(
             'local' => 'id',
             'foreign' => 'Role_id'));
    }
}