<?php

/**
 * Base_Route
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Contents
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Route extends Bal_Route
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Balcms_Content as Contents', array(
             'local' => 'id',
             'foreign' => 'Route_id'));
    }
}