<?php

/**
 * Base_Route
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $ContentList
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Route extends Bal_Route
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Balcms_Content as ContentList', array(
             'local' => 'id',
             'foreign' => 'route_id'));
    }
}