<?php

/**
 * Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property boolean $enabled
 * @property string $displayname
 * @property string $fullname
 * @property string $email
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $Roles
 * @property Doctrine_Collection $RoleAndUser
 * @property Doctrine_Collection $PermissionAndUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_User extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('username', 'string', 16, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '16',
             ));
        $this->hasColumn('password', 'string', 16, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '16',
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('displayname', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '50',
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notblank' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permission as Permissions', array(
             'refClass' => 'PermissionAndUser',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('Role as Roles', array(
             'refClass' => 'RoleAndUser',
             'local' => 'user_id',
             'foreign' => 'role_id'));

        $this->hasMany('RoleAndUser', array(
             'local' => 'id',
             'foreign' => 'assignee_user_id'));

        $this->hasMany('PermissionAndUser', array(
             'local' => 'id',
             'foreign' => 'assignee_user_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'username',
              1 => 'displayname',
              2 => 'fullname',
              3 => 'email',
             ),
             ));
        $this->actAs($softdelete0);
        $this->actAs($searchable0);
    }
}