<?php

/**
 * Base_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $InvoicesFor
 * @property Doctrine_Collection $InvoicesFrom
 * @property Doctrine_Collection $MessagesFor
 * @property Doctrine_Collection $MessagesFrom
 * @property Doctrine_Collection $Bal_RoleAndUser
 * @property Doctrine_Collection $Bal_PermissionAndUser
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_User extends Balcms_User
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Bal_Invoice as InvoicesFor', array(
             'local' => 'id',
             'foreign' => 'UserFor_id'));

        $this->hasMany('Bal_Invoice as InvoicesFrom', array(
             'local' => 'id',
             'foreign' => 'UserFrom_id'));

        $this->hasMany('Bal_Message as MessagesFor', array(
             'local' => 'id',
             'foreign' => 'UserFor_id'));

        $this->hasMany('Bal_Message as MessagesFrom', array(
             'local' => 'id',
             'foreign' => 'UserFrom_id'));

        $this->hasMany('Bal_RoleAndUser', array(
             'local' => 'id',
             'foreign' => 'UserFrom_id'));

        $this->hasMany('Bal_PermissionAndUser', array(
             'local' => 'id',
             'foreign' => 'UserFrom_id'));
    }
}