<?
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlBack = $this->bal()->getBaseUrl('back');
?>
<div class="wrap">
	<div id="icon-edit" class="icon32">
		<br/>
	</div>
	<h2>
		Editing
		<? foreach ( $this->ContentCrumbArray as $Content ): ?>
			&raquo; <a href="<?=$this->url(array('controller'=>'content','action'=>'content-list','content'=>$Content['code']),'admin')?>"><?=$Content['title']?></a>
		<? endforeach; ?>
	</h2>
	<?=$this->message()->render()?>
	<form name="post" action="post.php" method="post" id="post">
		<input type="hidden" id="_wpnonce" name="_wpnonce" value="b060cedf26" /><input type="hidden" name="_wp_http_referer" value="/wp-admin/post.php?action=edit&amp;post=1&amp;message=1" /><input type="hidden" id="user-id" name="user_ID" value="2212518" /><input type="hidden" id="hiddenaction" name="action" value="editpost" /><input type="hidden" id="originalaction" name="originalaction" value="editpost" /><input type="hidden" id="post_author" name="post_author" value="2212518" /><input type="hidden" id="post_type" name="post_type" value="post" /><input type="hidden" id="original_post_status" name="original_post_status" value="publish" /><input name="referredby" type="hidden" id="referredby" value="http://balupton.wordpress.com/wp-admin/post.php?action=edit&#038;post=1" /><input type="hidden" name="_wp_original_http_referer" value="http://balupton.wordpress.com/wp-admin/post.php?action=edit&amp;post=1" /><input type='hidden' id='post_ID' name='post_ID' value='1' />
		<div class="metabox-holder has-right-sidebar">
			<div id="side-info-column" class="inner-sidebar">
				<div id='side-sortables' class='meta-box-sortables sidebar-boxes'>
				
					<div id="sidebar-publish-box" class="postbox sidebar-box sidebar-box-sections">
						<h3><span>Publish</span></h3>
						<div class="inside">
							<div id="minor-publishing">
								<div id="minor-publishing-actions">
									<div id="save-action">
										<input name="save" id="save-post" value="Open" tabindex="4" class="button" type="submit">
									</div>
									<div id="preview-action">
										<a class="preview button" href="http://balupton.wordpress.com/?p=46&amp;preview=true" target="wp-preview" id="post-preview" tabindex="4">Preview</a>
									</div>
									<div class="clear"></div>
								</div>
								<div id="misc-publishing-actions">
									<div class="misc-pub-section field">
										<label for="content-status">Status:</label>
										<span id="content-status-view" class="field-value">Published</span>
										<span id="content-status-edit" class="hide">
											<br/>
											<select name="content[status]" id="content-status" tabindex="4">
												<option selected='selected' value='publish'>Published</option>
												<option value='pending'>Pending Review</option>
												<option value='draft'>Draft</option>
											</select>
										</span>
										<script type="text/javascript">
											$("#content-status-view").inlineEdit({
												edit: "#content-status-edit"
											});
										</script>
									</div>
									<div class="misc-pub-section misc-pub-section-last field" id="content-published_at-field">
										<label for="content-published_at">Publish<span class="weak">ed</span> on:</label>
										<span class="field-value" id="content-published_at-view">Nov 16, 2007 @ 1:53</span>
										<span id="content-published_at-edit" class="hide">
											<br/>
											<input type="text" name="content[published_at]" id="content-published_at" value="2009-05-11 11:53" class="sparkle-datetime"></input>
										</span>
										<script type="text/javascript">
											$("#content-published_at-view").inlineEdit({
												edit: "#content-published_at-edit"
											});
										</script>
									</div>
								</div>
								<div class="clear">
								</div>
							</div>
							<div id="major-publishing-actions">
								<div id="delete-action">
									<a class="delete" href="#">Delete</a>
								</div>
								<div id="publishing-action">
									<input name="save" type="submit" class="button-primary" id="publish" tabindex="5" accesskey="p" value="Save" />
								</div>
								<div class="clear">
								</div>
							</div>
						</div>
					</div>
					
					<div id="sidebar-tags-box" class="postbox sidebar-box">
						<h3>Post Tags</h3>
						<div class="inside">
							<label class="screen-reader-text" for="content-tags">Post Tags</label>
							<input id="content-tags" name="content[tags]" type="text" class="form-input-tip" autocomplete="off" value="Add tags" />
							<p class="description">
								Add your tags to the post above, separating them with commas.
							</p>
						</div>
					</div>
					
				</div>
			</div>
			<div id="post-body">
				<div id="post-body-content" class="field-container">
					<div id="content-title-field" class="field field-simple">
						<label class="screen-reader-text" for="title">
							Title
						</label>
						<input type="text" name="post_title" size="30" tabindex="1" value="<?=$this->ContentArray['title']?>" id="title" autocomplete="off" />
					</div>
					<div id="content-code-field" class="field field-little">
						<label for="post-content">
							Location:
						</label>
						<span class="inline-edit-clickable">http://www.mydance.com.au/</span><span id="content-code-view" title="Click to edit this part of the permalink" class="highlight"><?=$this->ContentArray['Route']['path']?></span><input type="text" name="content[code]" id="content-code-edit" value="<?=$this->ContentArray['Route']['path']?>" />/
						<span class="inline-edit-panel" id="content-code-panel"></span>
						<script type="text/javascript">
							$("#content-code-view").inlineEdit('editbutton', {
								edit: '#content-code-edit',
								panel: '#content-code-panel'
							});
						</script>
					</div>
					<div id="content-content-field" class="field field-rich">
						<textarea name="content" tabindex="2" id="content"><?=$Content['content']?></textarea>
						<script type="text/javascript">$(function(){$('#content').editor('rich');});</script>
					</div>
					<div id="content-description-field" class="field field-wrapper postbox widget">
						<div class="widget-top">Excerpt</div>
						<div class="inside">
							<textarea rows="3" cols="40" name="content[description]" tabindex="6" id="content-description"></textarea>
						</div>
						<script type="text/javascript">
							$('#content-description-field .widget-top').help('Excerpts are hand-crafted summaries of your content, they are used within such things as listings and search results.');
							$('#content-description').editor('simple');
						</script>
					</div>
				</div>
			</div>
			<br class="clear" />
		</div>
		<!-- /poststuff -->
	</form>
</div>
<div class="clear">
</div>