<?php

/**
 * Base_Balcms_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Content $Content
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Balcms_Message extends Bal_Message
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));
    }
}