<?php

/**
 * Base_Balcms_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $content_id
 * @property Content $Content
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Balcms_Message extends Bal_Message
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'Content_id',
             'foreign' => 'id'));
    }
}