<?php

/**
 * Base_Balcms_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Base_Balcms_User extends Bal_User
{
    public function setUp()
    {
        parent::setUp();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'username',
              1 => 'email',
              2 => 'fullname',
              3 => 'suburb',
              4 => 'state',
              5 => 'country',
             ),
             ));
        $this->actAs($searchable0);
    }
}