<div class="success jquery-hide-if-empty"><?
	if ( !empty($this->success) && !is_bool($this->success) ) {
		$messages = $this->success;
		if ( is_string($messages) ) $messages = array($messages);
		foreach ( $messages as $message ) {
			echo '<p>'.(is_array($message)?$this->locale->translate($message[0],$message[1]):$this->locale->translate($message[0],$message[1])).'</p>';
		}
	}
?></div>
<div class="error jquery-hide-if-empty"><?
	if ( !empty($this->error) && !is_bool($this->error) ) {
		$messages = $this->error;
		if ( is_string($messages) ) $messages = array($messages);
		foreach ( $messages as $message ) {
			echo '<p>'.(is_array($message)?$this->locale->translate($message[0],$message[1]):$this->locale->translate($message[0],$message[1])).'</p>';
		}
	}
?></div>