<?php
	echo $this->doctype();
	$baseUrl = $this->app()->getBaseUrl();
	$publicUrl = $this->app()->getPublicUrl();
	$jqueryUiUrl = $publicUrl.'/scripts/jquery-ui-1.7.2';
	$jquerySparkleUrl = $publicUrl.'/scripts/jquery-sparkle';
	$backUrl = $this->app()->getAreaUrl('back');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
    // CSS
    $this->headLink()
		->appendStylesheet($backUrl.'/styles/theme-login.css')
		->appendStylesheet($publicUrl.'/scripts/jquery-ui/css/cupertino/jquery-ui-1.7.2.custom.css');
    // Output
    echo $this->headLink();
    ?>
    <?=$this->headStyle()?>
</head>
<body class="login">
    <? // headScript
    echo $this->headScript()
	    // JSON
	    //->offsetSetFile(1,'http://www.json.org/json2.js')
	    // jQuery
	    ->offsetSetFile(2,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js' : $publicUrl.'/scripts/jquery-1.3.2.min.js')
	    // Application
	    ->offsetSetFile(5,$publicUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(6,$jquerySparkleUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetFile(7,$publicUrl.'/scripts/balcms/back.js')
	    // GSFN
	    ->offsetSetFile(80,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
	    ->offsetSetScript(81,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
	    // Configuration
	    ->offsetSetScript(101,'$.Help.applyConfig("default",{icon: \'<img src="'.$backUrl.'/images/help.png" alt="help" class="help-icon" />\'});')
    ?>
	<?=$this->layout()->content?>
</body>
</html>