<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>

<div style="margin:10px;" id="error">
	<h1>An error occurred</h1>
	<h2><?= $this->locale()->translate($this->error) ?></h2>
	
	<h3>Exception information:</h3>
	<p>
		<strong>Message:</strong>
		<span class="message">
			<? if ( empty($this->messages) ): ?>
				<pre><?= $this->locale()->translate($this->exception->getMessage()) ?></pre>
			<? else: ?>
				<? foreach ( $this->messages as $message ): ?>
					<?
						$message['field'] = $this->locale()->translate($message['table'].'-field-'.$message['field']);
						$message['plural'] = $this->locale()->translate($message['table'].'-title-plural');
						$message['singular'] = $this->locale()->translate($message['table'].'-title-singular');
						$message['ownership'] = $this->locale()->translate($message['table'].'-title-ownership');
					?>
					<?= $this->locale()->translate($message['code'], $message) ?><br />
				<? endforeach; ?>
			<? endif; ?>
		</span>
	</p>

	<? if ( DEBUG_MODE ): ?>
		<h3>Stack trace:</h3>
		<pre><?= $this->exception->getTraceAsString() ?>
		</pre>
		
		<h3>Request Parameters:</h3>
		<pre><? var_dump($this->request->getParams()) ?>
		</pre>
		
		<? if ( !empty($this->profiler) ) : ?>
			<h3>Profiler:</h3>
			<pre><?
				$time = 0;
				foreach ( $this->profiler as $event) {
				    $time += $event->getElapsedSecs();
				    echo $event->getName() . " " . sprintf("%f", $event->getElapsedSecs()) . "\n";
				    echo $event->getQuery() . "\n";
				    $params = $event->getParams();
				    if( ! empty($params)) {
				        print_r($params);
				    }
				}
				echo "Total time: " . $time  . "\n";
			?></pre>
		<? endif; ?>
		
		<? if ( !empty($this->identity) ) : ?>
			<h3>Identity:</h3>
			<pre><?= var_export($this->identity,true) ?>
			</pre>
		<? endif; ?>
		
		<? if ( !empty($this->permissions) ) : ?>
			<h3>Permissions:</h3>
			<pre><?= var_export($this->permissions,true) ?>
			</pre>
		<? endif; ?>
	<? endif; ?>
</div>

</body>
</html>