<?php
	echo $this->doctype();
	$publicUrl = $this->app()->getPublicUrl();
	$frontUrl = $this->app()->getAreaUrl('front');
?>
<html>
<head>
    <?= $this->headTitle() ?>
    <?= $this->headLink()
		->setStylesheet($publicUrl.'/styles/error.css') ?>
    <?= $this->headStyle() ?>
    <?= $this->headScript() ?>
<style type="text/css">
dt {
	margin-top:1em;
}
</style>
</head>
<body>

<div style="margin:10px;" id="error">
	<h1>An error occurred</h1>
	<h2><?= $this->locale()->translate($this->error) ?></h2>

<dl>
	<dt>Exception information:</dt>
	<dd>
		<span class="message">
			<? if ( empty($this->messages) ): ?>
				<pre><?= $this->locale()->translate($this->exception->getMessage()) ?></pre>
			<? else: ?>
				<? foreach ( $this->messages as $message ): ?>
					<?
						$message['field'] = $this->locale()->translate($message['table'].'-field-'.$message['field']);
						$message['plural'] = $this->locale()->translate($message['table'].'-title-plural');
						$message['singular'] = $this->locale()->translate($message['table'].'-title-singular');
						$message['ownership'] = $this->locale()->translate($message['table'].'-title-ownership');
					?>
					<?= $this->locale()->translate($message['code'], $message) ?><br />
				<? endforeach; ?>
			<? endif; ?>
		</span>
	</dd>

	<? if ( DEBUG_MODE ): ?>
		<dt>Stack trace:</dt>
		<dd><?= Bal_Debug::render($this->exception->getTraceAsString()) ?></dd>
		
		<dt>Request Parameters (raw):</dt>
		<dd><?= Bal_Debug::render($_REQUEST) ?></dd>
		
		<dt>Server Parameters (raw):</dt>
		<dd><?= Bal_Debug::render($_SERVER) ?></dd>
		
		<? if ( !empty($this->profiler) ) : ?>
			<h3>Profiler:</h3>
			<dd><?
				$time = 0;
				foreach ( $this->profiler as $event) {
				    $time += $event->getElapsedSecs();
				    echo $event->getName() . " " . sprintf("%f", $event->getElapsedSecs()) . "\n";
				    echo $event->getQuery() . "\n";
				    $params = $event->getParams();
				    if( ! empty($params)) {
				        print_r($params);
				    }
				}
				echo "Total time: " . $time  . "\n";
			?></dd>
		<? endif; ?>
		
		<? if ( !empty($this->identity) ) : ?>
			<dt>Identity:</dt>
			<dd><?= Bal_Debug::render($this->identity) ?></dd>
		<? endif; ?>
		
		<? if ( !empty($this->permissions) ) : ?>
			<dt>Permissions:</dt>
			<dd><?= Bal_Debug::render($this->permissions) ?></dd>
		<? endif; ?>
	<? endif; ?>
	
	</dl>
</div>

</body>
</html>