<div class="articlelist">
	<? foreach ( $this->ContentList as $Content ) :
		$contentUrl = $this->url()->content($Content)->toString();
		?>
		<div class="articlelist-content">
			<h3>
				<a href="<?=$contentUrl?>" title="<?=$Content->title?>">
					<?=$this->locale()->date($Content->event_start_at).' - '.$Content->title?>
				</a>
			</h3>
			<div class="articlelist-content-content">
				<?=$this->content()->renderDescription($Content)?>
			</div>
		</div>
	<? endforeach; ?>
</div>