<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$title = !empty($this->title) ? $this->title : 'Popular Tags';
?><div class="recentlist widget">
	<div class="recentlist-header widget-header">
		<h3><?=$title?></h3>
	</div>
	<? foreach ( $this->ContentList as $Content ) :
		$contentUrl = $this->url()->content($Content)->toString();
		?>
		<div class="recentlist-content widget-content">
			<h4 class="recentlist-content-header widget-content-header"><a rel="nofollow" href="<?=$contentUrl?>" title="<?=$Content->title?>"><?=$Content->title?></a></h4>
			<div class="recentlist-content-content widget-content-content">
				<?=strip_tags($Content->description)?>
			</div>
		</div>
	<? endforeach; ?>
	<div class="clear"></div>
</div>