<div class="recentlist widget">
	<div class="recentlist-header widget-header">
		<h3>Recent Items</h3>
	</div>
	<? foreach ( $this->ContentList as $Content ) :
		$contentUrl = $this->content()->getContentUrl($Content);
		?>
		<div class="recentlist-content widget-content">
			<h4 class="recentlist-content-header widget-content-header"><a rel="nofollow" href="<?=$contentUrl?>" title="<?=$Content->title?>"><?=$Content->title?></a></h4>
			<div class="recentlist-content-content widget-content-content">
				<?=strip_tags($Content->description)?>
			</div>
		</div>
	<? endforeach; ?>
	<div class="clear"></div>
</div>