<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
<body class="email">
	<div class="email-wrapper">
		<div class="email-header">
			<p>You're receiving this email because it matches your subscription prefrences on <a href="#">MyDance.com.au</a>.</p>
			<p>Having trouble reading this email? <a href="#">View it on your browser</a>. Not interested anymore? <a href="#">Unsubscribe Instantly</a>.</p>
		</div>
		<div class="email-body">
			<h1 class="email-title"><?=$this->ContentArray['title']?></h1>
			<div class="email-content">
				<?=$this->ContentArray['content_rendered']?>
			</div>
		</div>
		<div class="email-footer">
			<p>myDance.com.au... tagline asdasd asd asd</p>
		</div>
	</div>
</body>
</html>