<?
	# Prepare
	$this->url()->renege('route','front');
	$base_url = $this->app()->getBaseUrl();
	$mode = delve($this,'mode','full');
	# Content
	$Content = delve($this,'Content');
	$Content_code = delve($Content,'code');
	$Content_title = delve($Content,'title');
	$Content_tagline = delve($Content,'tagline');
	$Content_type = delve($Content,'type');
	$Content_published_at = delve($Content,'published_at');
	$Content_url = $this->url()->content($Content)->toString();
	# Author
	$Content_Author = delve($Content,'Author');
	$Content_Author_displayname = delve($Content_Author,'displayname');
	$Content_Author_url = $this->url()->user($Content_Author)->toString();
	# Avatar
	$Content_Avatar = delve($Content,'Avatar');
	# Ancestors
	$Content_Ancestors = delve($this,'Content_Ancestors',$Content->getAncestors(false));
	$Content_Ancestors = $Content->toNavItems($Content_Ancestors);
	array_unshift($Content_Ancestors,array(
		'label' => 'Home',
		'title' => 'Home',
		'uri' => $base_url
	));
	# Children
	$Content_Children = delve($this,'Content_Children',$Content->getChildren(false));
	$Content_Children = $Content->toNavItems($Content_Children);
	if ( !$Content_Children ) $Content_Children = $Content->getSectionLinks();
	# Related
	$Content_Related = delve($this,'Content_Related',array());
	# Comments
	$Content_Comments = delve($this,'Content_Comments',array());
	# Tags
	$Content_ContentTags = delve($Content,'ContentTags',array());
	# Class
	if ( empty($class) )
		$class = array();
	elseif ( !is_array($class) )
		$class = array($class);
	$class[] = 'article';
	if ( $mode === 'article' ) {
		$class[] = 'main';
	}
	$class[] = 'content-'.$Content_type;
	$Comment_article_class = implode(' ',array_unique($class));
	# Id
	$Content_article_id = 'content-'.$Content_code;
?>
<article
	cite="<?=$Content_url?>"
	pubdate="<?=date('c',strtotime($Content_published_at))?>"
	id="<?=$Content_article_id?>"
	class="<?=$Comment_article_class?>"
	>
	
	<header class="article-header header">
		<?=$this->partial('partials/nav-links.phtml',array(
			'class' => 'simple nav-ancestors',
			'Items' => $Content_Ancestors
		))?>
		<a class="article-title" href="<?=$Content_url?>" title="<?=$Content_title?>">
			<h1>
				<span class="title"><?=$Content_title?></span>
				<span class="description"><?=$Content_tagline?></span>
			</h1>
		</a>
		<?=$this->partial('partials/nav-links.phtml',array(
			'class' => 'simple nav-children',
			'Items' => $Content_Children
		))?>
		<?=$this->partial('partials/nav-tags.phtml',array(
			'class' => 'simple nav-tags',
			'Items' => $Content_ContentTags
		))?>
	</header>
	
	<? if ( delve($Content_Avatar,'id') ) :
		$Content_Avatar_url = $this->url()->media($Content_Avatar)->toString();
		?>
		<div class="article-avatar avatar">
			<a href="<?=$Content_Avatar_url?>" title="View Image">
				<img src="<?=$Content_Avatar_url?>?width=200" title="<?=$Content_title?>" alt="<?=$Content_title?> Avatar" />
			</a>
		</div>
	<? endif; ?>
	
	<!-- [more] -->
	<? if ( in_array($mode,array('article')) ) : ?>
		<div class="article-content">
			<?=$this->content()->renderContentContent($Content)?>
		</div>

		<footer class="article-footer footer">
			<ul class="article-details details">
				<li class="article-published published">
					<span class="title">Published At</span>
					<a class="description" href="<?=$Content_url?>"><time datetime="<?=date('c',strtotime($Content_published_at))?>" pubdate>
						<?=$this->locale()->datetime($Content_published_at)?>
					</time></a>
				</li>
	
				<li class="article-author author">
					<span class="title">Author</span>
					<a class="description" href="<?=$Content_Author_url?>">
						<?=$Content_Author_displayname?>
					</a>
				</li>
			</ul>
		
			<?=$this->partial('partials/comments.phtml',array(
				'class' => 'article-comments',
				'Items' => $Content_Comments
			))?>
		</footer>
	<? endif; ?>
	
	<? if ( in_array($mode,array('list')) ) : ?>
		<div class="article-description">
			<?=$this->content()->renderContentDescription($Content)?>
			<a class="more" href="<?=$Content_url?>">Continue Reading</a>
		</div>
	<? endif; ?>
	<!-- [/more] -->
	
</article>