<?
	# Prepare
	$this->url()->renege('route','front');
	$base_url = $this->app()->getBaseUrl();
	$mode = delve($this,'mode','full');
	# Content
	$Content = delve($this,'Content');
	$Content_code = delve($Content,'code');
	$Content_title = delve($Content,'title');
	$Content_tagline = delve($Content,'tagline');
	$Content_type = delve($Content,'type');
	$Content_published_at = delve($Content,'published_at');
	$Content_url = $this->url()->content($Content)->toString();
	# Author
	$Content_Author = delve($Content,'Author');
	$Content_Author_displayname = delve($Content_Author,'displayname');
	$Content_Author_description = delve($Content_Author,'description');
	$Content_Author_Avatar = delve($Content_Author,'Avatar',array());
	$Content_Author_url = $this->url()->user($Content_Author)->toString();
	# Avatar
	$Content_Avatar = delve($Content,'Avatar',array());
	# Ancestors
	$Content_Ancestors = delve($this,'Content_Ancestors',$Content->getAncestors(false));
	$Content_Ancestors = $Content->toNavItems($Content_Ancestors);
	array_unshift($Content_Ancestors,array(
		'label' => 'Home',
		'title' => 'Home',
		'uri' => $base_url
	));
	# Children
	$Content_Children = delve($this,'Content_Children',$Content->getChildren(false));
	$Content_Children = $Content->toNavItems($Content_Children);
	if ( !$Content_Children ) $Content_Children = $Content->getSectionLinks();
	# Related
	$Content_Related = delve($this,'Content_Related',array());
	# Comments
	$Content_Comments = delve($this,'Content_Comments',array());
	# Tags
	$Content_ContentTags = delve($Content,'ContentTags',array());
	# Class
	if ( empty($class) )
		$class = array();
	elseif ( !is_array($class) )
		$class = array($class);
	$class[] = 'article';
	$class[] = 'content-'.$Content_type;
	$class[] = 'mode-'.$mode;
	$Content_article_class = implode(' ',array_unique($class));
	# Id
	$Content_article_id = 'content-'.$Content_code;
?>
<article
	cite="<?=$Content_url?>"
	pubdate="<?=date('c',strtotime($Content_published_at))?>"
	id="<?=$Content_article_id?>"
	class="<?=$Content_article_class?>"
	>
	
	<header class="article-header header">
		<?=$this->partial('partials/nav-links.phtml',array(
			'class' => 'simple nav-ancestors',
			'Items' => $Content_Ancestors
		))?>
		<h1 class="article-title">
			<a href="<?=$Content_url?>" title="<?=$Content_title.' > '.$Content_tagline?>">
				<span class="title"><?=$Content_title?></span>
				<span class="description"><?=$Content_tagline?></span>
			</a>
		</h1>
		<?=$this->partial('partials/nav-links.phtml',array(
			'class' => 'simple nav-children',
			'Items' => $Content_Children
		))?>
		<?=$this->partial('partials/nav-tags.phtml',array(
			'class' => 'simple nav-tags',
			'Items' => $Content_ContentTags
		))?>
	</header>
	
	<? if ( !reallyempty($Content_Avatar) ) :
		$Content_Avatar_url = $this->url()->media($Content_Avatar)->toString();
		?>
		<div class="article-avatar avatar">
			<a href="<?=$Content_Avatar_url?>" title="View Image">
				<img src="<?=$Content_Avatar_url?>?width=200" title="<?=$Content_title?>" alt="<?=$Content_title?>'s Avatar" />
			</a>
		</div>
	<? endif; ?>
	
	<!-- [more] -->
	<? if ( in_array($mode,array('article')) ) : ?>
		<div class="article-content">
			<?=Content::renderContent($Content)?>
		</div>

		<!-- Footer -->
		<footer class="article-footer footer" id="article-footer">
			
			<!-- Header -->
			<header class="header"><h1>
				<span class="title">The End.</span>
			</h1></header>
			
			<!-- Published -->
			<section class="article-published section" id="article-published">
				<header class="header">
					<h1><span class="title">Published</span></h1>
				</header>
				
				<p class="published">
					<span class="title">Published on</span>
					<a class="description" href="<?=$Content_url?>"><time datetime="<?=date('c',strtotime($Content_published_at))?>" pubdate>
						<?=$this->locale()->date($Content_published_at, Zend_Date::DATE_LONG)?>
						@
						<?=$this->locale()->date($Content_published_at, Zend_Date::TIME_SHORT)?>
						<?=$this->locale()->date($Content_published_at, Zend_Date::TIMEZONE)?>
					</time></a>
				</p>
			</section>
			
			<!-- Author -->
			<section class="article-author section" id="article-author">
				<header class="header">
					<h1><span class="title">About the Author</span></h1>
				</header>
				
				<p class="author-title">
					<span class="title">Written by</span>
					<a class="description" href="<?=$Content_Author_url?>">
						<?=$Content_Author_displayname?>
					</a>
				</p>
				
				<? if ( $Content_Author_description ) : ?>
					<? if ( !reallyempty($Content_Author_Avatar) ) :
						$Content_Author_Avatar_url = $this->url()->media($Content_Author_Avatar)->toString();
						?>
						<div class="author-avatar avatar">
							<a href="<?=$Content_Author_Avatar_url?>" title="View Image">
								<img src="<?=$Content_Author_Avatar_url?>?width=200" title="<?=$Content_Author_displayname?>" alt="<?=$Content_Author_displayname?>'s Avatar" />
							</a>
						</div>
					<? endif; ?>
					
					<p class="author-description"><?=$Content_Author_description?></p>
				
				<? endif; ?>
			</section>
			
			<!-- Comments -->
			<? if ( delve($Content,'comments_enabled',false) ) : ?>
				<section class="article-comments section" id="article-comments">
					<header class="header">
						<h1><span class="title">Comments</span></h1>
					</header>
			
					<div class="article-comments-content">
						<div id="disqus_thread"></div>
						<script type="text/javascript">
							var disqus_identifier = "<?=format_to_output(delve($Content,'code'),'jsattr')?>";
							var disqus_developer = 1;
							var disqus_url = "<?=format_to_output($Content_url,'jsattr')?>";
							(function() {
								var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
								dsq.src = 'http://balupton.disqus.com/embed.js';
								(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
							})();
						</script>
						<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript=balupton">comments powered by Disqus.</a></noscript>
					</div>
				</section>
			<? endif; ?>
		</footer>
	<? endif; ?>
	
	<? if ( in_array($mode,array('list')) ) : ?>
		<div class="article-description">
			<div class="article-description-content">
				<?=Content::renderDescription($Content)?>
			</div>
			<div class="article-description-more">
				<a href="<?=$Content_url?>" title="View the entire article">Continue Reading</a>
			</div>
		</div>
	<? endif; ?>
	<!-- [/more] -->
	
</article>