<?
	# Fetch
	$title = delve($this,'title');
	$class = pass_by_copy('array_values_ensure',delve($this,'class'),array('nav'));
	$class_item = delve($this,'class_item','link');
	$Items = delve($this,'Items',array());
	$class[] = empty($Items) ? 'empty' : 'notempty';
	$class = implode(' ',$class);
?>
<nav class="<?=$class?>">
	<header class="header">
		<h1><?=$title?></h1>
	</header>
	<?=$this->app()->getNavigationMenu($Items)
		->setTemplate('<span class="title">$label</span>')
		->render()?>
</nav>