<div class="eventlist">
	<div class="eventlist-past">
		<? if ( count($this->EventsPast) ) : ?>
			<div class="eventlist-title"><h3>Past:</h3></div>
			<? foreach ( $this->EventsPast as $Content ) : ?>
				<div class="eventlist-content">
					<h3><a href="<?=$this->content()->getUrl($Content)?>" title="<?=$Content->title?>"><?=$Content->title?></a></h3>
					<div class="eventlist-content-content">
						<?=$this->content()->renderDescription($Content)?>
					</div>
				</div>
			<? endforeach; ?>
		<? endif; ?>
	</div>
	<div class="eventlist-future">
		<? if ( count($this->EventsFuture) ) : ?>
			<div class="eventlist-title"><h3>Future:</h3></div>
			<? foreach ( $this->EventsFuture as $Content ) : ?>
				<div class="eventlist-content">
					<h3><a href="<?=$this->content()->getUrl($Content)?>" title="<?=$Content->title?>"><?=$Content->title?></a></h3>
					<div class="eventlist-content-content">
						<?=$this->content()->renderDescription($Content)?>
					</div>
				</div>
			<? endforeach; ?>
		<? endif; ?>
	</div>
</div>