<?
$key = $this->key;
$Item = $this->Item;
$value = $Item->get($key);
$Table = $Item->getTable();
$type = $Table->getTypeOf($key);
$properties = $Table->getDefinitionOf($key);

if ( is_object($value) ) {
	if ( !empty($value->id) ) {
		$Relation = $value;
		$RelationTable = $Relation->getTable();
		$value = $RelationTable->hasField('title')
			?	$Relation->title
			:	(
				$RelationTable->hasField('name')
				?	$Relation->name
				:	(
					$RelationTable->hasField('code')
					?	$Relation->code
					:	(
						$RelationTable->hasField('fullname')
						?	$Relation->fullname
						:	$Relation->id
						)
					)
				)
			;
	} else {
		$value = null;
	}
}

if ( !empty($properties['extra']) && !empty($properties['extra']['currency']) )
	$type = 'currency';

switch($type):
	case 'boolean':
		echo $value?'Yes':'No';
		break;
	case 'currency':
		echo $this->locale->currency($value);
		break;
	default:
		echo $value;
		break;
endswitch;
?>