<?
// Prepare
$Item = $this->Item;

// Handle
if ( $Item->hasFeature('list') ):
	echo $this->show('helpers/items/list.phtml', array('Item'=>$Item));
else: ?>
	<div class="post" id="page-<?=$Item->id?>">
		<div class="post-header">
			<div class="date">
				<?=$Item->created?> <span><?=date('Y', strtotime($Item->published))?></span>
			</div>
			<h2><a href="<?=$this->url(array('item'=>$Item->code), 'item')?>" rel="bookmark" title="Permanent Link to <?=$Item->title?>">
				<?=$Item->title?>
			</a></h2>
			<div class="author">
				by <?=$Item->Author->username?>
			</div>
		</div>
		<div class="entry clear">
			<?=$Item->content?>
		</div>
		<div class="post-footer">
			<div class="comments">
				<span>Comments Off</span>
			</div>
		</div>
	</div><?
endif;
