
                    <div class="wrap">
                        <div id="icon-edit-pages" class="icon32">
                            <br>
                        </div>
                        <h2>Edit Pages</h2>
                        <form id="posts-filter" action="" method="get">
                            <ul class="subsubsub">
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php" class="current">All <span class="count">(1)</span></a>
                                    |
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php?post_status=publish">Published <span class="count">(1)</span></a>
                                    |
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php?post_status=future">Scheduled <span class="count">(0)</span></a>
                                    |
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php?post_status=pending">Pending Review <span class="count">(0)</span></a>
                                    |
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php?post_status=draft">Drafts <span class="count">(0)</span></a>
                                    |
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php?post_status=private">Private <span class="count">(0)</span></a>
                                </li>
                            </ul>
                            <p class="search-box">
                                <label class="screen-reader-text" for="page-search-input">
                                    Search Pages:
                                </label>
                                <input id="page-search-input" name="s" type="text"><input value="Search Pages" class="button" type="submit">
                            </p>
                            <div class="tablenav">
                                <div class="alignleft actions">
                                    <select name="action">
                                        <option value="-1" selected="selected">Bulk Actions</option>
                                        <option value="edit">Edit</option>
                                        <option value="delete">Delete</option>
                                    </select>
                                    <input value="Apply" name="doaction" id="doaction" class="button-secondary action" type="submit"><input id="_wpnonce" name="_wpnonce" value="44c4e08b11" type="hidden"><input name="_wp_http_referer" value="/wordpress/wp-admin/edit-pages.php" type="hidden">
                                </div>
                                <br class="clear">
                            </div>
                            <div class="clear">
                            </div>
                            <table class="widefat page fixed" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                                            <input type="checkbox">
                                        </th>
                                        <th scope="col" id="title" class="manage-column column-title" style="">
                                            Title
                                        </th>
                                        <th scope="col" class="manage-column column-author" style="">
                                            Description
                                        </th>
                                        <th scope="col" id="author" class="manage-column column-author" style="">
                                            Author
                                        </th>
                                        <th scope="col" id="comments" class="manage-column column-comments num" style="">
                                            <div class="vers">
                                                <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                                            </div>
                                        </th>
                                        <th scope="col" id="date" class="manage-column column-date" style="">
                                            Date
                                        </th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th scope="col" class="manage-column column-cb check-column" style="">
                                            <input type="checkbox">
                                        </th>
                                        <th scope="col" class="manage-column column-title" style="">
                                            Title
                                        </th>
                                        <th scope="col" class="manage-column column-author" style="">
                                            Description
                                        </th>
                                        <th scope="col" class="manage-column column-author" style="">
                                            Author
                                        </th>
                                        <th scope="col" class="manage-column column-comments num" style="">
                                            <div class="vers">
                                                <img alt="" src="edit-pages.php_files/comment-grey-bubble.png">
                                            </div>
                                        </th>
                                        <th scope="col" class="manage-column column-date" style="">
                                            Date
                                        </th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    <tr id="page-2" class="alternate iedit">
                                        <th scope="row" class="check-column">
                                            <input name="post[]" value="2" type="checkbox">
                                        </th>
                                        <td class="post-title page-title column-title">
                                            <strong><a class="row-title" href="http://localhost/wordpress/wp-admin/page.php?action=edit&amp;post=2" title="Edit “About”">
                                            	Welcome
											</a></strong>
                                        </td>
                                        <td class="author column-author">
                                            <strong>System Page:</strong> Welcome
                                        </td>
                                        <td class="author column-author">
                                            <a href="http://localhost/wordpress/wp-admin/edit-pages.php?author=1">premala</a>
                                        </td>
                                        <td class="comments column-comments">
                                            <div class="post-com-count-wrapper">
                                                <a href="http://localhost/wordpress/wp-admin/edit-comments.php?p=2" title="0 pending" class="post-com-count"><span class="comment-count">0</span></a>
                                            </div>
                                        </td>
                                        <td class="date column-date">
                                            <abbr title="2009/10/01 8:46:55 AM">
                                                8 mins ago
                                            </abbr>
                                            <br>
                                            Published
                                        </td>
                                    </tr>
                                    <tr id="page-2" class="alternate iedit">
                                        <th scope="row" class="check-column">
                                            <input name="post[]" value="2" type="checkbox">
                                        </th>
                                        <td class="post-title page-title column-title">
                                            <strong><a class="row-title" href="http://localhost/wordpress/wp-admin/page.php?action=edit&amp;post=2" title="Edit “About”">
                                            	About Us
											</a></strong>
                                        </td>
                                        <td class="author column-author">
                                            <strong>Content Page</strong>
                                        </td>
                                        <td class="author column-author">
                                            <a href="http://localhost/wordpress/wp-admin/edit-pages.php?author=1">premala</a>
                                        </td>
                                        <td class="comments column-comments">
                                            <div class="post-com-count-wrapper">
                                                <a href="http://localhost/wordpress/wp-admin/edit-comments.php?p=2" title="0 pending" class="post-com-count"><span class="comment-count">0</span></a>
                                            </div>
                                        </td>
                                        <td class="date column-date">
                                            <abbr title="2009/10/01 8:46:55 AM">
                                                8 mins ago
                                            </abbr>
                                            <br>
                                            Published
                                        </td>
                                    </tr>
                                    <tr id="page-2" class="alternate iedit">
                                        <th scope="row" class="check-column">
                                            <input name="post[]" value="2" type="checkbox">
                                        </th>
                                        <td class="post-title page-title column-title">
                                            <strong><a class="row-title" href="http://localhost/wordpress/wp-admin/page.php?action=edit&amp;post=2" title="Edit “About”">
                                            	Events
											</a></strong>
                                        </td>
                                        <td class="author column-author">
                                            <strong>System Page:</strong> Events
                                        </td>
                                        <td class="author column-author">
                                            <a href="http://localhost/wordpress/wp-admin/edit-pages.php?author=1">premala</a>
                                        </td>
                                        <td class="comments column-comments">
                                            <div class="post-com-count-wrapper">
                                                <a href="http://localhost/wordpress/wp-admin/edit-comments.php?p=2" title="0 pending" class="post-com-count"><span class="comment-count">0</span></a>
                                            </div>
                                        </td>
                                        <td class="date column-date">
                                            <abbr title="2009/10/01 8:46:55 AM">
                                                8 mins ago
                                            </abbr>
                                            <br>
                                            Published
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <div class="tablenav">
                                <div class="alignleft actions">
                                    <select name="action2">
                                        <option value="-1" selected="selected">Bulk Actions</option>
                                        <option value="edit">Edit</option>
                                        <option value="delete">Delete</option>
                                    </select>
                                    <input value="Apply" name="doaction2" id="doaction2" class="button-secondary action" type="submit">
                                </div>
                                <br class="clear">
                            </div>
                        </form>
                        <form method="get" action="">
                            <table style="display: none;">
                                <tbody id="inlineedit">
                                    <tr id="inline-edit" class="inline-edit-row inline-edit-row-page quick-edit-row quick-edit-row-page" style="display: none;">
                                        <td colspan="5">
                                            <fieldset class="inline-edit-col-left">
                                                <div class="inline-edit-col">
                                                    <h4>Quick Edit</h4>
                                                    <label>
                                                        <span class="title">Title</span>
                                                        <span class="input-text-wrap"><input name="post_title" class="ptitle" type="text"></span>
                                                    </label>
                                                    <label>
                                                        <span class="title">Slug</span>
                                                        <span class="input-text-wrap"><input name="post_name" type="text"></span>
                                                    </label>
                                                    <label>
                                                        <span class="title">Date</span>
                                                    </label>
                                                    <div class="inline-edit-date">
                                                        <select name="mm" tabindex="4">
                                                            <option value="01">Jan</option>
                                                            <option value="02">Feb</option>
                                                            <option value="03">Mar</option>
                                                            <option value="04">Apr</option>
                                                            <option value="05">May</option>
                                                            <option value="06">Jun</option>
                                                            <option value="07">Jul</option>
                                                            <option value="08">Aug</option>
                                                            <option value="09">Sep</option>
                                                            <option value="10" selected="selected">Oct</option>
                                                            <option value="11">Nov</option>
                                                            <option value="12">Dec</option>
                                                        </select>
                                                        <input name="jj" value="01" size="2" maxlength="2" tabindex="4" autocomplete="off" type="text">, <input name="aa" value="2009" size="4" maxlength="4" tabindex="4" autocomplete="off" type="text">@ <input name="hh" value="08" size="2" maxlength="2" tabindex="4" autocomplete="off" type="text">: <input name="mn" value="46" size="2" maxlength="2" tabindex="4" autocomplete="off" type="text"><input id="ss" name="ss" value="55" type="hidden">
                                                    </div>
                                                    <br class="clear">
                                                    <div class="inline-edit-group">
                                                        <label class="alignleft">
                                                            <span class="title">Password</span>
                                                            <span class="input-text-wrap"><input name="post_password" class="inline-edit-password-input" type="text"></span>
                                                        </label><em style="margin: 5px 10px 0pt 0pt;" class="alignleft">–OR– </em>
                                                        <label class="alignleft inline-edit-private">
                                                            <input name="keep_private" value="private" type="checkbox"><span class="checkbox-title">Private page</span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <fieldset class="inline-edit-col-right">
                                                <div class="inline-edit-col">
                                                    <label>
                                                        <span class="title">Parent</span>
                                                        <select name="post_parent" id="post_parent">
                                                            <option selected="selected" value="0">Main Page (no parent)</option>
                                                            <option class="level-0" value="2">About</option>
                                                        </select>
                                                    </label>
                                                    <label>
                                                        <span class="title">Order</span>
                                                        <span class="input-text-wrap"><input name="menu_order" class="inline-edit-menu-order-input" value="0" type="text"></span>
                                                    </label>
                                                    <label>
                                                        <span class="title">Template</span>
                                                        <select name="page_template">
                                                            <option selected="selected" value="default">Default Template</option>
                                                            <option value="archives.php">Archives</option>
                                                            <option value="links.php">Links</option>
                                                        </select>
                                                    </label>
                                                    <div class="inline-edit-group">
                                                        <label class="alignleft">
                                                            <input name="comment_status" value="open" type="checkbox"><span class="checkbox-title">Allow Comments</span>
                                                        </label>
                                                        <label class="alignleft">
                                                            <input name="ping_status" value="open" type="checkbox"><span class="checkbox-title">Allow Pings</span>
                                                        </label>
                                                    </div>
                                                    <div class="inline-edit-group">
                                                        <label class="inline-edit-status alignleft">
                                                            <span class="title">Status</span>
                                                            <select name="_status">
                                                                <option selected="selected" value="publish">Published</option>
                                                                <option value="future">Scheduled</option>
                                                                <option value="pending">Pending Review</option>
                                                                <option value="draft">Draft</option>
                                                            </select>
                                                        </label>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <p class="submit inline-edit-save">
                                                <a accesskey="c" href="#inline-edit" title="Cancel" class="button-secondary cancel alignleft">Cancel</a>
                                                <input id="_inline_edit" name="_inline_edit" value="7b95aa0652" type="hidden"><a accesskey="s" href="#inline-edit" title="Update" class="button-primary save alignright">Update Page</a>
                                                <img class="waiting" style="display: none;" src="edit-pages.php_files/wpspin_light.gif" alt=""><input name="post_view" value="list" type="hidden">
                                                <br class="clear">
                                            </p>
                                        </td>
                                    </tr>
                                    <tr id="bulk-edit" class="inline-edit-row inline-edit-row-page bulk-edit-row bulk-edit-row-page" style="display: none;">
                                        <td colspan="5">
                                            <fieldset class="inline-edit-col-left">
                                                <div class="inline-edit-col">
                                                    <h4>Bulk Edit Pages</h4>
                                                    <div id="bulk-title-div">
                                                        <div id="bulk-titles">
                                                        </div>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <fieldset class="inline-edit-col-right">
                                                <div class="inline-edit-col">
                                                    <label>
                                                        <span class="title">Parent</span>
                                                        <select name="post_parent" id="post_parent">
                                                            <option selected="selected" value="-1">- No Change -</option>
                                                            <option value="0">Main Page (no parent)</option>
                                                            <option class="level-0" value="2">About</option>
                                                        </select>
                                                    </label>
                                                    <label>
                                                        <span class="title">Template</span>
                                                        <select name="page_template">
                                                            <option selected="selected" value="-1">- No Change -</option>
                                                            <option value="default">Default Template</option>
                                                            <option value="archives.php">Archives</option>
                                                            <option value="links.php">Links</option>
                                                        </select>
                                                    </label>
                                                    <div class="inline-edit-group">
                                                        <label class="alignleft">
                                                            <span class="title">Comments</span>
                                                            <select name="comment_status">
                                                                <option selected="selected" value="">- No Change -</option>
                                                                <option value="open">Allow</option>
                                                                <option value="closed">Do not allow</option>
                                                            </select>
                                                        </label>
                                                        <label class="alignright">
                                                            <span class="title">Pings</span>
                                                            <select name="ping_status">
                                                                <option selected="selected" value="">- No Change -</option>
                                                                <option value="open">Allow</option>
                                                                <option value="closed">Do not allow</option>
                                                            </select>
                                                        </label>
                                                    </div>
                                                    <div class="inline-edit-group">
                                                        <label class="inline-edit-status alignleft">
                                                            <span class="title">Status</span>
                                                            <select name="_status">
                                                                <option selected="selected" value="-1">- No Change -</option>
                                                                <option value="publish">Published</option>
                                                                <option value="private">Private</option>
                                                                <option value="pending">Pending Review</option>
                                                                <option value="draft">Draft</option>
                                                            </select>
                                                        </label>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <p class="submit inline-edit-save">
                                                <a accesskey="c" href="#inline-edit" title="Cancel" class="button-secondary cancel alignleft">Cancel</a>
                                                <input accesskey="s" class="button-primary alignright" name="bulk_edit" value="Update Pages" type="submit"><input name="post_view" value="list" type="hidden">
                                                <br class="clear">
                                            </p>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                        <div id="ajax-response">
                        </div>
                    </div>