<?php
	// Doctype
	echo $this->doctype('HTML5');
	// URL
	$base_url_full = $this->app()->getBaseUrl(true);
	$base_url = $this->app()->getBaseUrl();
	$public_url = $this->app()->getPublicUrl();
	$back_url = $this->app()->getAreaUrl('back');
	$front_url = $this->app()->getAreaUrl('front');
	$script_url = $public_url.'/scripts';
	$jquery_ui_url = $script_url.'/jquery-ui-1.7.2';
	$jquery_sparkle_url = $script_url.'/jquery-sparkle';
	$tiny_mce_url = $script_url.'/tiny_mce-3.2.7';
	$this->url()->renege('route','back');
	// Identity
	$Identity = $this->app()->getUser();
?><html>
<head>
    <?= $this->app()->headMeta() ?>
    <?= $this->app()->headTitle() ?>
    <?= $this->app()->headLink()->appendStylesheet($jquery_ui_url.'/css/cupertino/jquery-ui-1.7.2.custom.css') ?>
    <?= $this->app()->headStyle() ?>
</head>
<body>
    <?
		$headScript = $this->app()->headScript()
		    // jQuery
			->offsetSetFile(20,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js' : $public_url.'/scripts/jquery-1.4.2.js')
			// UI
			->offsetSetFile(30,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js' : $jquery_ui_url.'/js/jquery-ui-1.7.2.custom.min.js')
		    // TinyMCE
			->offsetSetFile(40,$tiny_mce_url.'/jquery.tinymce.js')
			->offsetSetScript(200,'$.Editor.applyConfig("default",{script_url: "'.$tiny_mce_url.'/tiny_mce.js", content_css: "'.$front_url.'/styles/content.css"});')
		    // Application
		    ->offsetSetFile(50,$public_url.'/scripts/jquery.autogrow.js')
		    ->offsetSetFile(60,$jquery_sparkle_url.'/scripts/jquery.sparkle.js')
		    ->offsetSetScript(65,'if ( typeof JSON === "undefined" ) $.appendScript("'.$script_url.'/json2.js");')
			->offsetSetScript(201,'$.Help.applyConfig("default",{icon: \'<img src="'.$back_url.'/images/help.png" alt="help" class="help-icon" />\'});')
			// Ajaxy
			//->appendFile($base_url.'/scripts/ajaxy/js/jquery.history.js')->appendFile($base_url.'/scripts/ajaxy/js/jquery.ajaxy.js')
			;
		if ( APPLICATION_ENV !== 'development' )
			$headScript
				// GSFN
		    	->offsetSetFile(80,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
		    	->offsetSetScript(81,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
				;
	    echo $headScript;
    ?>
        <div id="wpwrap">
            <div id="wpcontent">
                <div id="wphead">
                    <!--<img id="header-logo" src="edit-pages.php_files/blank.gif" alt="" height="32" width="32">-->
                    <h1 id="site-heading"><a href="<?=$base_url_full?>" title="Visit Site">
                    	<span id="site-title"><?=$this->app()->getConfig('bal.site.name')?></span>
                    	<em id="site-visit-button">Visit Site</em>
                    </a></h1>
                    <div id="wphead-info">
                        <div id="user_info">
                            <p>
                                User: <?=delve($Identity,'displayname')?>
                                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                                | <a href="<?=$this->url(array('action'=>'logout'),'back',true)?>" title="Log Out">Log Out</a>
                            </p>
                        </div>
	                    <?=true?'':$this->app()->getNavigationMenu('back.fav')->setPartial(array('navigation/favorites.phtml', 'default'))->render()?>
                    </div>
                </div>
                <div id="wpbody">
					<?
					
					try { echo $this->app()->getNavigationMenu('back.main')->setPartial(array('navigation/menu.phtml', 'default'))->render(); }
					catch ( Exception $e ) {
						echo $e->getMessage();
						die;
					}				
					?>
					<div id="wpbody-content">
                        <?= $this->layout()->content?>
                        <div class="clear">
                        </div>
                    </div>
                    <!-- wpbody-content -->
                    <div class="clear">
                    </div>
                </div>
                <!-- wpbody -->
                <div class="clear">
                </div>
            </div>
            <!-- wpcontent -->
        </div>
        <!-- wpwrap -->
        <div id="footer">
            <p id="footer-left" class="alignleft">
                <span id="footer-thankyou">Thank you for creating with <a href="<?=$this->url(array(),'balcmshome',true)?>">balCMS</a>.</span>
                | <a href="<?=$this->url(array(),'balcmsdocs',true)?>">Documentation</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>">Support</a>
            </p>
            <p id="footer-upgrade" class="alignright">
                Version <?=$this->app()->getConfig('bal.site.version')?>
            </p>
            <div class="clear">
            </div>
        </div>
	</body>
</html>