<?php
	echo $this->doctype('HTML5');
	$baseFullUrl = $this->app()->getBaseUrl(true);
	$baseUrl = $this->app()->getBaseUrl();
	$publicUrl = $this->app()->getPublicUrl();
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	$jqueryUiUrl = $publicUrl.'/scripts/jquery-ui-1.7.2';
	$jquerySparkleUrl = $publicUrl.'/scripts/jquery-sparkle';
	$tinyMceUrl = $publicUrl.'/scripts/tiny_mce-3.2.7';
	$User = $this->app()->getUser();
?><html>
<head>
    <?= $this->app()->headMeta() ?>
    <?= $this->app()->headTitle() ?>
    <?= $this->app()->headLink()->appendStylesheet($jqueryUiUrl.'/css/cupertino/jquery-ui-1.7.2.custom.css') ?>
    <?= $this->app()->headStyle() ?>
</head>
<body>
    <?= $this->app()->headScript()
	    // JSON
	    //->offsetSetFile(1,'http://www.json.org/json2.js')
		// jQuery
		->offsetSetFile(20,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js' : $publicUrl.'/scripts/jquery-1.4.1.min.js')
		// UI
		->offsetSetFile(30,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js' : $jqueryUiUrl.'/js/jquery-ui-1.7.2.custom.min.js')
	    // Ajaxy
		//->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.history.js')->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.ajaxy.js')
		// TinyMCE
		->offsetSetFile(40,$tinyMceUrl.'/jquery.tinymce.js')
		->offsetSetScript(200,'$.Editor.applyConfig("default",{script_url: "'.$tinyMceUrl.'/tiny_mce.js", content_css: "'.$frontUrl.'/styles/content.css"});')
	    // GSFN
	    ->offsetSetFile(80,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
	    ->offsetSetScript(81,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
	    // Application
	    ->offsetSetFile(50,$publicUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(60,$jquerySparkleUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetScript(201,'$.Help.applyConfig("default",{icon: \'<img src="'.$backUrl.'/images/help.png" alt="help" class="help-icon" />\'});')
    ?>
        <div id="wpwrap">
            <div id="wpcontent">
                <div id="wphead">
                    <!--<img id="header-logo" src="edit-pages.php_files/blank.gif" alt="" height="32" width="32">-->
                    <h1 id="site-heading"><a href="<?=$baseFullUrl?>" title="Visit Site">
                    	<span id="site-title"><?=$this->app()->getConfig('bal.site.name')?></span>
                    	<em id="site-visit-button">Visit Site</em>
                    </a></h1>
                    <div id="wphead-info">
                        <div id="user_info">
                            <p>
                                User: <?=$User['displayname']?>
                                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                                | <a href="<?=$this->url(array('action'=>'logout'),'back',true)?>" title="Log Out">Log Out</a>
                            </p>
                        </div>
	                    <?=true?'':$this->navigation()->menu()->setPartial(array('navigation/favorites.phtml', 'default'))->setContainer($this->NavigationFavorites)->render()?>
                    </div>
                </div>
                <div id="wpbody">
					<?=$this->navigation()->menu()->setPartial(array('navigation/menu.phtml', 'default'))->setContainer($this->NavigationMenu)->render()?>
					<div id="wpbody-content">
                        <?= $this->layout()->content?>
                        <div class="clear">
                        </div>
                    </div>
                    <!-- wpbody-content -->
                    <div class="clear">
                    </div>
                </div>
                <!-- wpbody -->
                <div class="clear">
                </div>
            </div>
            <!-- wpcontent -->
        </div>
        <!-- wpwrap -->
        <div id="footer">
            <p id="footer-left" class="alignleft">
                <span id="footer-thankyou">Thank you for creating with <a href="<?=$this->url(array(),'balcmshome',true)?>">balCMS</a>.</span>
                | <a href="<?=$this->url(array(),'balcmsdocs',true)?>">Documentation</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>">Support</a>
            </p>
            <p id="footer-upgrade" class="alignright">
                Version <?=$this->app()->getConfig('bal.site.version')?>
            </p>
            <div class="clear">
            </div>
        </div>
	</body>
</html>