<?php
	echo $this->doctype();
	$baseUrl = $this->app()->getBaseUrl();
	$publicUrl = $this->app()->getPublicUrl();
	$jqueryUiUrl = $publicUrl.'/scripts/jquery-ui-1.7.2';
	$jquerySparkleUrl = $publicUrl.'/scripts/jquery-sparkle';
	$backUrl = $this->app()->getAreaUrl('back');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?=$this->app()->headMeta()?>
    <?=$this->app()->headTitle()?>
    <?=$this->app()->headLink()->appendStylesheet($jqueryUiUrl.'/css/cupertino/jquery-ui-1.7.2.custom.css') ?>
    <?=$this->app()->headStyle()?>
</head>
<body>
    <?= $this->app()->headScript()
	    // JSON
	    //->offsetSetFile(1,'http://www.json.org/json2.js')
		// jQuery
		->offsetSetFile(20,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js' : $publicUrl.'/scripts/jquery-1.4.1.min.js')
		// UI
		//->offsetSetFile(30,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js' : $jqueryUiUrl.'/js/jquery-ui-1.7.2.custom.min.js')
	    // Application
	    ->offsetSetFile(50,$publicUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(60,$jquerySparkleUrl.'/scripts/jquery.sparkle.js')
	    // GSFN
	    ->offsetSetFile(80,'http://s3.amazonaws.com/getsatisfaction.com/javascripts/feedback-v2.js')
	    ->offsetSetScript(81,"var GSFN_feedback_widget = new GSFN.feedback_widget({ display: 'overlay', company: 'balupton', placement: 'hidden', color: '#222', style: 'question' });")
	    // Configuration
	    ->offsetSetScript(201,'$.Help.applyConfig("default",{icon: \'<img src="'.$backUrl.'/images/help.png" alt="help" class="help-icon" />\'});')
    ?>
	<?=$this->layout()->content?>
</body>
</html>