<?
	# URLs
	$back_url = $this->app()->getAreaUrl('back');
	$front_url = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	
	# Users
	$ItemList = delve($this,'ItemList');
	$ItemListFields = delve($this,'ItemListFields');
	$ItemListFieldsExclusive = $ItemListFields;
	$ItemListLabelField = array_shift($ItemListFieldsExclusive);
	
	# Type
	$type = delve($this,'type','user');
	$Type = ucfirst($type);
	
	# Title
	$this->headTitle()->append($Type);
	
?><div class="wrap">
	<!-- Edit Button -->
    <div id="icon-edit-pages" class="icon32">
        <br/>
    </div>
	<!-- Header -->
    <h2>
		<a href="<?=$this->url()->action('crud-list')->param('type',$type)?>"><?=$Type?> List</a>
		<a class="button add-new-h2" href="<?=$this->url()->action('crud-new')->param('type',$type)?>">Create New</a>
	</h2>
    <!-- Filters -->
    <form id="posts-filter" action="<?=$this->url()->action('crud-list')->param('type',$type)->search()?>" method="get">
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="search-query">
                Search:
            </label>
			<?=$this->formText('search[query]',delve($this,'search.query'),array())?>
			<?=$this->formSubmit('search[submit]','Search',array('class'=>'button'))?>
        </p>
        <div class="clear">
        </div>
		<?=$this->log()->render()?>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        <?=$Type?>
                    </th>
					<? foreach ( $ItemListFieldsExclusive as $ItemListField ) : ?>
                    <th scope="col" id="title" class="manage-column" style="">
                        <?=$ItemListField?>
                    </th>
					<? endforeach; ?>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" id="title" class="manage-column column-title" style="">
                        <?=$Type?>
                    </th>
					<? foreach ( $ItemListFieldsExclusive as $ItemListField ) : ?>
                    <th scope="col" id="title" class="manage-column" style="">
                        <?=$ItemListField?>
                    </th>
					<? endforeach; ?>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="content-list">
            	<? foreach ( $ItemList as $_Item ): ?>
            	<?
					$_Item_id = delve($_Item,'id');
					$_Item_label = delve($_Item,$ItemListLabelField);
            		$_Item_url = $this->url()->action('crud-view')->param('type',$type)->item($_Item)->toString();
            		$_Item_url_edit = $this->url()->action('crud-edit')->param('type',$type)->item($_Item)->toString();
            		$_Item_url_delete = $this->url()->action('crud-delete')->param('type',$type)->item($_Item)->toString();
            	?>
                <tr id="content-<?=$_Item_id?>" class="<?=$this->cycle(array('','alternate'), 'ContentTree')->next()?>">
                	<td class="column-icon media-icon">
						<a title="View <?=$_Item_label?>" href="<?=$_Item_url?>">
							<? if ( false ): ?>
								<img width="46" height="60" title="<?=$_Item_label?>" alt="" class="attachment-80x60" src="<?=$back_url?>/images/files/default.png"/>
							<? endif; ?>
						</a>
					</td>
                    <td class="post-title page-title column-title">
						<?=$this->formHidden('item[id]', $_Item_id)?>
                        <strong><a class="row-title" href="<?=$_Item_url_edit?>" title="Open this">
                        	<?=$_Item_label?>
						</a></strong>
						<div class="row-actions">
							<?
								$_Item_actions = array();
								
								if ( delve($this,'ItemListEditable',true) )
									$_Item_actions[] = '<span class="edit"><a title="Edit" href="'.$_Item_url_edit.'">Edit</a></span>';
								
								if ( delve($this,'ItemListDeletable',true) )
									$_Item_actions[] = '<span class="delete"><a class="delete-action" title="Are you sure you want to delete '.$_Item_label.'" href="'.$_Item_url_delete.'">Delete</a></span>';
								
								echo implode(' | ', $_Item_actions);
							?>
						</div>
                    </td>
					<? foreach ( $ItemListFieldsExclusive as $ItemListField ) : ?>
                    <th scope="col" id="title" class="manage-column" style="">
                        <?
							$_value = delve($_Item,$ItemListField);
							if ( !$_value )
								$_value = $this->locale()->translate('empty');
							elseif ( is_array($_value) || is_object($_value) ) {
								$_label = $this->app()->getItemLabel($_value);
								if ( empty($_label) && is_traversable($_value) && $this->app()->getItemLabel($_value[0]) ) {
									$_labels = array();
									foreach ( $_value as $__value ) {
										$_labels[] = $this->app()->getItemLabel($__value);
									}
									$_value = implode(', ', $_labels);
								} else {
									$_value = $_label;
								}
							}
							echo $_value;
						?>
                    </th>
					<? endforeach; ?>
                </tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
</div>