<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$id = delve($this,'id');
	$class = delve($this,'class');
	$title = delve($this,'title','ContentList');
	$ContentList = delve($this,'ContentList',array());
?>
<section id="<?=$id?>" class="widget widget-contentlist <?=$class?> section">
    <header class="widget-header section-header header">
        <h1><span class="title"><?=$title?></span></h1>
    </header>
    <div class="widget-content">
		<? foreach ( $ContentList as $Content ) : ?>
			<?
				echo $this->partial('partials/content.phtml',array(
					'Content' => $Content,
					'mode' => 'list'
				));
			?>
		<? endforeach; ?>
    </div>
</section>