<?
	// URLs
	$baseFullUrl = $this->app()->getBaseUrl(true);
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	
	// Identity
	$Identity = $this->app()->getUser();
	$Identity_id = delve($Identity,'id');
	
	// User
	$User = delve($this,'User');
	$User_id = delve($User,'id');
	$User_code = delve($User,'code');
	$User_uid = delve($User,'uid');
	$User_username = delve($User,'username');
	$User_displayname = delve($User,'code');
	$self = $User_id === $Identity_id;
	$selfstr = $self ? 'your' : 'their';
	
	// Crumbs
	$ItemCrumbs = delve($this,'ItemCrumbs',array($User));
	
	// Mode
	$mode = delve($User,'id') ? 'edit' : 'new';
	$mode_edit = $mode === 'edit';
	
	// Type
	$type = delve($this,'type');
	$Type = ucfirst($type);
	
	// Form
	$Form = delve($this,'Form');
	$Form_title = $Form->getLegend(); if ( !$Form_title ) $Form_title = $Type;
	$Form_title = ($mode_edit ? 'Editing' : 'New').' '.$Form_title.($mode_edit ? ': '.$User_username : '');
	$Form_description = $Form->getDescription();
	
	// Title
	$this->headTitle()->append($Type);
	$this->headTitle()->append(delve($User,'username','New'));
?>
<div class="wrap" id="profile-page">
	
	<div id="icon-users" class="icon32">
		<br>
	</div>
	
	<h2>
		<? if ( $self ): ?>
			<?= (ucfirst($selfstr) . ' Profile') ?>
		<? else: ?>
			<?=$mode_edit?'Editing':'Create New '.$Type?>
			<? if ( $mode_edit ) foreach ( $ItemCrumbs as $_Item ): ?>
				&raquo; <a href="<?=$this->url()->user($_Item)?>"><?=$this->app()->getItemLabel($_Item)?></a>
			<? endforeach; ?>
		<? endif; ?>
	</h2>
	
	<? if ( $Form_description ) : ?>
	<p>
		<?=$Form_description?>
	</p>
	<? endif; ?>
	
	<? if ( $mode_edit ) : ?>
	<p>
		<?=ucfirst($selfstr)?> API key is: <code><?=$User_uid?></code>. Don't share <?=$selfstr?> API key, it's like a password.
	</p>
	<? endif; ?>
	
	<?=$this->log()->render()?>
	
	<?=$Form->render()?>
	
	<script type="text/javascript">
		$(function(){
			var $password = $('#user-password');
			var $passwordStrength = $('<div id="user-password-strength"></div>');
			$passwordStrength.appendTo($password.parent());
			$passwordStrength.passwordStrength({
				'password': $password,
				//'confirm':  '#user-password-confirm',
				'username': '#user-username',
				il8n: {
					hint: ''
				}
			});
		});
	</script>
</div>