<?php
	echo $this->doctype();
	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?=$this->headMeta()?>
	<?=$this->headTitle()?>
	<?	// CSS
		$this->headLink()
			->appendStylesheet($baseUrl.'/scripts/extjs/resources/css/ext-all.css');
		// Output
		echo $this->headLink(); ?>
	<?=$this->headStyle()?>
</head>
<body>

<?= $this->headScript()
	// JSON
	->appendFile('http://www.json.org/json2.js')
	// jQuery
	->appendFile(APPLICATION_ENV==='production'?'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js':$baseUrl.'/scripts/jquery-1.3.2.min.js')
	// UI
	->appendFile(APPLICATION_ENV==='production'?'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js':$baseUrl.'/scripts/jquery-ui/js/jquery-ui-1.7.2.custom.min.js')
	// Ajaxy
	->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.history.js')
	->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.ajaxy.js')
	// Application
	->appendFile($baseUrl.'/scripts/jquery.sparkle.js')
	->appendFile($baseUrl.'/scripts/balcms/balcms.js')
	?>
	
<body class="wp-admin js  edit-pages-php">
    <script type="text/javascript">
        //<![CDATA[
        (function(){
            var c = document.body.className;
            c = c.replace(/no-js/, 'js');
            document.body.className = c;
        })();
        //]]>
    </script>
    <div id="wpwrap">
        <div id="wpcontent">
            <div id="wphead">
                <img id="header-logo" src="edit-pages.php_files/blank.gif" alt="" height="32" width="32"><h1 id="site-heading"><a href="http://localhost/wordpress/" title="Visit Site"><span id="site-title">balPress</span><em id="site-visit-button">Visit Site</em></a></h1>
                <div id="wphead-info">
                    <div id="user_info">
                        <p>
                            Howdy, <a href="http://localhost/wordpress/wp-admin/profile.php" title="Edit your profile">admin</a>
                            <span style="display: inline;" class="turbo-nag hidden"> | <a href="http://localhost/wordpress/wp-admin/tools.php">Turbo</a></span>
                            |<a href="http://localhost/wordpress/wp-login.php?action=logout&amp;_wpnonce=4a471fc4e5" title="Log Out">Log Out</a>
                        </p>
                    </div>
                    <div id="favorite-actions">
                        <div id="favorite-first">
                            <a href="http://localhost/wordpress/wp-admin/page-new.php">New Page</a>
                        </div>
                        <div id="favorite-toggle">
                            <br>
                        </div>
                        <div style="width: 126px;" id="favorite-inside">
                            <div class="favorite-action">
                                <a href="http://localhost/wordpress/wp-admin/post-new.php">New Post</a>
                            </div>
                            <div class="favorite-action">
                                <a href="http://localhost/wordpress/wp-admin/edit.php?post_status=draft">Drafts</a>
                            </div>
                            <div class="favorite-action">
                                <a href="http://localhost/wordpress/wp-admin/media-new.php">Upload</a>
                            </div>
                            <div class="favorite-action">
                                <a href="http://localhost/wordpress/wp-admin/edit-comments.php">Comments</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="wpbody">
                <ul id="adminmenu">
                    <li class="wp-first-item menu-top menu-top-first menu-top-last" id="menu-dashboard">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/index.php">
                                <br>
                            </a>
                        </div>
                        <div style="display: none;" class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/index.php" class="wp-first-item menu-top menu-top-first menu-top-last" tabindex="1">Dashboard</a>
                    </li>
                    <li class="wp-menu-separator">
                        <a class="separator" href="http://localhost/wordpress/wp-admin/edit-pages.php?unfoldmenu=1">
                            <br>
                        </a>
                    </li>
                    <li class="wp-has-submenu open-if-no-js menu-top menu-top-first" id="menu-posts">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/edit.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/edit.php" class="wp-has-submenu open-if-no-js menu-top menu-top-first" tabindex="1">Posts</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Posts
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/edit.php" class="wp-first-item" tabindex="1">Edit</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/post-new.php" tabindex="1">Add New</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-tags.php?taxonomy=post_tag" tabindex="1">Post Tags</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/categories.php" tabindex="1">Categories</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top" id="menu-media">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/upload.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/upload.php" class="wp-has-submenu menu-top" tabindex="1">Media</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Media
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/upload.php" class="wp-first-item" tabindex="1">Library</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/media-new.php" tabindex="1">Add New</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top" id="menu-links">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/link-manager.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/link-manager.php" class="wp-has-submenu menu-top" tabindex="1">Links</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Links
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/link-manager.php" class="wp-first-item" tabindex="1">Edit</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/link-add.php" tabindex="1">Add New</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/edit-link-categories.php" tabindex="1">Link Categories</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu wp-has-current-submenu wp-menu-open menu-top" id="menu-pages">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/edit-pages.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/edit-pages.php" class="wp-has-submenu wp-has-current-submenu wp-menu-open menu-top" tabindex="1">Pages</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Pages
                            </div>
                            <ul>
                                <li class="wp-first-item current">
                                    <a href="http://localhost/wordpress/wp-admin/edit-pages.php" class="wp-first-item current" tabindex="1">Edit</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/page-new.php" tabindex="1">Add New</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="menu-top menu-top-last" id="menu-comments">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/edit-comments.php">
                                <br>
                            </a>
                        </div>
                        <div style="display: none;" class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/edit-comments.php" class="menu-top menu-top-last" tabindex="1">Comments <span id="awaiting-mod" class="count-0"><span class="pending-count">0</span></span></a>
                    </li>
                    <li class="wp-menu-separator">
                        <a class="separator" href="http://localhost/wordpress/wp-admin/edit-pages.php?unfoldmenu=1">
                            <br>
                        </a>
                    </li>
                    <li class="wp-has-submenu menu-top menu-top-first" id="menu-appearance">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/themes.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/themes.php" class="wp-has-submenu menu-top menu-top-first" tabindex="1">Appearance</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Appearance
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/themes.php" class="wp-first-item" tabindex="1">Themes</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/widgets.php" tabindex="1">Widgets</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/theme-editor.php" tabindex="1">Editor</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/theme-install.php" tabindex="1">Add New Themes</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/themes.php?page=functions.php" tabindex="1">Custom Header</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top" id="menu-plugins">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/plugins.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/plugins.php" class="wp-has-submenu menu-top" tabindex="1">Plugins <span class="update-plugins count-0"><span class="plugin-count">0</span></span></a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Plugins <span class="update-plugins count-0"><span class="plugin-count">0</span></span>
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/plugins.php" class="wp-first-item" tabindex="1">Installed</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/plugin-install.php" tabindex="1">Add New</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/plugin-editor.php" tabindex="1">Editor</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top" id="menu-users">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/users.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/users.php" class="wp-has-submenu menu-top" tabindex="1">Users</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Users
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/users.php" class="wp-first-item" tabindex="1">Authors &amp; Users</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/user-new.php" tabindex="1">Add New</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/profile.php" tabindex="1">Your Profile</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top" id="menu-tools">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/tools.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/tools.php" class="wp-has-submenu menu-top" tabindex="1">Tools</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Tools
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/tools.php" class="wp-first-item" tabindex="1">Tools</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/import.php" tabindex="1">Import</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/export.php" tabindex="1">Export</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/update-core.php" tabindex="1">Upgrade</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-has-submenu menu-top menu-top-last" id="menu-settings">
                        <div class="wp-menu-image">
                            <a href="http://localhost/wordpress/wp-admin/options-general.php">
                                <br>
                            </a>
                        </div>
                        <div class="wp-menu-toggle">
                            <br>
                        </div>
                        <a href="http://localhost/wordpress/wp-admin/options-general.php" class="wp-has-submenu menu-top menu-top-last" tabindex="1">Settings</a>
                        <div class="wp-submenu">
                            <div class="wp-submenu-head">
                                Settings
                            </div>
                            <ul>
                                <li class="wp-first-item">
                                    <a href="http://localhost/wordpress/wp-admin/options-general.php" class="wp-first-item" tabindex="1">General</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-writing.php" tabindex="1">Writing</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-reading.php" tabindex="1">Reading</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-discussion.php" tabindex="1">Discussion</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-media.php" tabindex="1">Media</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-privacy.php" tabindex="1">Privacy</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-permalink.php" tabindex="1">Permalinks</a>
                                </li>
                                <li>
                                    <a href="http://localhost/wordpress/wp-admin/options-misc.php" tabindex="1">Miscellaneous</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="wp-menu-separator-last">
                        <a class="separator" href="http://localhost/wordpress/wp-admin/edit-pages.php?unfoldmenu=1">
                            <br>
                        </a>
                    </li>
                </ul>
                <div id="wpbody-content">
                    <div id="screen-meta">
                        <div id="screen-options-wrap" class="hidden">
                            <form id="adv-settings" action="" method="post">
                                <h5>Show on screen</h5>
                                <div class="metabox-prefs">
                                    <label for="author-hide">
                                        <input class="hide-column-tog" name="author-hide" id="author-hide" value="author" checked="checked" type="checkbox">Author
                                    </label>
                                    <label for="comments-hide">
                                        <input class="hide-column-tog" name="comments-hide" id="comments-hide" value="comments" checked="checked" type="checkbox">Comments
                                    </label>
                                    <label for="date-hide">
                                        <input class="hide-column-tog" name="date-hide" id="date-hide" value="date" checked="checked" type="checkbox">Date
                                    </label>
                                    <br class="clear">
                                </div>
                                <h5>Options</h5>
                                <div class="screen-options">
                                    <label for="edit_pages_per_page">
                                        Pages per page:
                                    </label>
                                    <input class="screen-per-page" name="wp_screen_options[value]" id="edit_pages_per_page" maxlength="3" value="20" type="text"><input class="button" value="Apply" type="submit"><input name="wp_screen_options[option]" value="edit_pages_per_page" type="hidden">
                                </div>
                                <div>
                                    <input id="screenoptionnonce" name="screenoptionnonce" value="f146b799a3" type="hidden">
                                </div>
                            </form>
                        </div>
                        <div id="contextual-help-wrap" class="hidden">
                            <h5>Help</h5>
                            <div class="metabox-prefs">
                                <a href="http://codex.wordpress.org/" target="_blank">Documentation</a>
                                <br>
                                <a href="http://wordpress.org/support/" target="_blank">Support Forums</a>
                            </div>
                        </div>
                        <div id="screen-meta-links">
                            <div id="contextual-help-link-wrap" class="hide-if-no-js screen-meta-toggle">
                                <a href="#contextual-help" id="contextual-help-link" class="show-settings">Help</a>
                            </div>
                            <div id="screen-options-link-wrap" class="hide-if-no-js screen-meta-toggle">
                                <a href="#screen-options" id="show-settings-link" class="show-settings">Screen Options</a>
                            </div>
                        </div>
                    </div>
					<?=$this->layout()->content?>
                    <div class="clear">
                    </div>
                </div>
                <!-- wpbody-content -->
                <div class="clear">
                </div>
            </div>
            <!-- wpbody -->
            <div class="clear">
            </div>
        </div>
        <!-- wpcontent -->
    </div>
    <!-- wpwrap -->
    <div id="footer">
        <p id="footer-left" class="alignleft">
            <span id="footer-thankyou">Thank you for creating with <a href="http://wordpress.org/">WordPress</a>.</span>
            | <a href="http://codex.wordpress.org/">Documentation</a>
            | <a href="http://wordpress.org/support/forum/4">Feedback</a>
        </p>
        <p id="footer-upgrade" class="alignright">
            Version 2.8.4
        </p>
        <div class="clear">
        </div>
    </div>
</html>