<?php
	echo $this->doctype();
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlBack = $this->bal()->getBaseUrl('back');
	$User = $this->bal()->getUser();
?><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?= $this->headMeta()?>
    <?= $this->headTitle()?>
    <?
    // CSS
    $this->headLink()
		//->appendStylesheet($baseUrl.'/back/styles/wp-admin.css')
		->appendStylesheet($baseUrl.'/back/styles/load-styles.css')
		->appendStylesheet($baseUrl.'/back/styles/colors-fresh.css')
		->appendStylesheet($baseUrl.'/back/styles/balcms.css')
		->appendStylesheet($baseUrl.'/scripts/jquery-ui/css/cupertino/jquery-ui-1.7.2.custom.css');
    // Output
    echo $this->headLink();
    ?>
    <?= $this->headStyle()?>
</head>
<body class="wp-admin js edit-pages-php">
    <? // headScript
    echo $this->headScript()
	    // JSON
	    ->offsetSetFile(1,'http://www.json.org/json2.js')
	    // jQuery
	    ->offsetSetFile(2,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js' : $baseUrl.'/scripts/jquery-1.3.2.min.js')
	    // UI
	    ->offsetSetFile(3,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js' : $baseUrl.'/scripts/jquery-ui/js/jquery-ui-1.7.2.custom.min.js')
	    // Ajaxy
		//->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.history.js')->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.ajaxy.js')
		// TinyMCE
		->offsetSetFile(4,$baseUrl.'/scripts/tiny_mce/jquery.tinymce.dev.js')
		->offsetSetScript(100,'$.Editor.applyConfig("default",{script_url: "'.$baseUrl.'/scripts/tiny_mce/tiny_mce.js"});')
	    // Application
	    ->offsetSetFile(5,$baseUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(6,$baseUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetFile(7,$baseUrlBack.'/scripts/cms.js')
	    ->offsetSetScript(101,'$.Help.applyConfig("default",{icon: \'<img src="'.$baseUrl.'/images/help.png" alt="help" class="help-icon" />\'});')
    ?>
        <div id="wpwrap">
            <div id="wpcontent">
                <div id="wphead">
                    <!--<img id="header-logo" src="edit-pages.php_files/blank.gif" alt="" height="32" width="32">-->
                    <h1 id="site-heading"><a href="<?=$baseUrl?>" title="Visit Site">
                    	<span id="site-title"><?=$this->bal()->config('bal.site.name')?></span>
                    	<em id="site-visit-button">Visit Site</em>
                    </a></h1>
                    <div id="wphead-info">
                        <div id="user_info">
                            <p>
                                User: <?=$User['displayname']?>
                                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                                | <a href="<?=$this->url(array('action'=>'logout'),'admin',true)?>" title="Log Out">Log Out</a>
                            </p>
                        </div>
	                    <?=true?'':$this->navigation()->menu()->setPartial(array('navigation/favorites.phtml', 'default'))->setContainer($this->NavigationFavorites)->render()?>
                    </div>
                </div>
                <div id="wpbody">
					<?=$this->navigation()->menu()->setPartial(array('navigation/menu.phtml', 'default'))->setContainer($this->NavigationMenu)->render()?>
					<div id="wpbody-content">
                        <?= $this->layout()->content?>
                        <div class="clear">
                        </div>
                    </div>
                    <!-- wpbody-content -->
                    <div class="clear">
                    </div>
                </div>
                <!-- wpbody -->
                <div class="clear">
                </div>
            </div>
            <!-- wpcontent -->
        </div>
        <!-- wpwrap -->
        <div id="footer">
            <p id="footer-left" class="alignleft">
                <span id="footer-thankyou">Thank you for creating with <a href="<?=$this->url(array(),'balcmshome',true)?>">balCMS</a>.</span>
                | <a href="<?=$this->url(array(),'balcmsdocs',true)?>">Documentation</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>" class="gsfn">Feedback</a>
                | <a href="<?=$this->url(array(),'balcmshelp',true)?>">Support</a>
                <!-- | <a href="<?=$this->url(array('action'=>'about'),'admin',true)?>">About</a> -->
            </p>
            <p id="footer-upgrade" class="alignright">
                Version 0.1.0-dev Movember
            </p>
            <div class="clear">
            </div>
        </div>
		<!-- GetSatisfaction -->
		<script type="text/javascript" charset="utf-8">
			// Insert Widget
			(function(){
				var is_ssl = ("https:" == document.location.protocol);
				var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
				document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
			})();
		</script>
		<script type="text/javascript" charset="utf-8">
			var feedback_widget = false;
			// Load Widget
			(function(){
				var feedback_widget_options = {
					display: 'overlay',
					company: 'balupton',
					placement: 'hidden',
					color: '#222',
					style: 'question'
				};
				feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
			})();
			// Apply Action
			$(function(){
				$('.feedback-action').click(function(event){
					if ( typeof feedback_widget === 'object' ) {
						feedback_widget.show();
						// Prevent
						//event.stopPropagation();
						event.preventDefault();
						return false;
					}
				});
			});
		</script>
	</body>
</html>