<?php
	echo $this->doctype();
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlFront = $this->bal()->getBaseUrl('front');
	$User = $this->bal()->getUser();
?><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?= $this->headMeta()?>
    <?= $this->headTitle()?>
    <?
    // CSS
    $this->headLink()
		->appendStylesheet($baseUrlFront.'/styles/skin.css')
		;
    // Output
    echo $this->headLink();
    ?>
    <?= $this->headStyle()?>
</head>
<body class="">
    <? // headScript
    echo $this->headScript()
	    // JSON
	    ->offsetSetFile(1,'http://www.json.org/json2.js')
	    // jQuery
	    ->offsetSetFile(2,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js' : $baseUrl.'/scripts/jquery-1.3.2.min.js')
	    // Ajaxy
		//->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.history.js')->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.ajaxy.js')
		// Application
	    //->offsetSetFile(5,$baseUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(6,$baseUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetFile(7,$baseUrl.'/scripts/cms/front.js')
	    ;
    ?>
<body>
	<div id="main">
		
		<div id="header">
			<div id="logo"><h1><?=$this->bal()->getConfig('bal.site.name')?></h1></div>
			
			<div id="nav-top" class="nav-action">
				<?=$this->navigation()->menu()->renderMenu($this->NavigationActions,array('ulClass'=>'ul-unstyled-horizontal'))?>
			</div>
			
			<div id="nav-search" class="nav-action">
				<form action="<?=$this->url(array('action'=>'search'),'app',true)?>" method="GET" >
					<label for="search">Search</label>
					<input type="text" name="search" id="search" title="Search query" class="sparkle-hint"  />
				</form>
			</div>
			
			<div id="nav-subscribe" class="nav-action">
				<form action="<?=$this->url(array('action'=>'subscribe'),'app',true)?>" method="POST" >
					<label for="email">Newsletter</label>
					<input type="text" name="email" id="email" title="Your email" class="sparkle-hint"  />
				</form>
			</div>
			
			<div class="clear"></div>
		</div>
		
		<div id="nav-main">
			<?=$this->navigation()->menu()->renderMenu($this->NavigationMenu,array('ulClass'=>'ul-unstyled-horizontal'))?>
		</div>
		
		<div id="content-wrap">
			<?=$this->layout()->content?>
		</div>
		
		<div id="footer">
			<div id="footer-links">
				<?=$this->navigation()->menu()->renderMenu($this->NavigationFooter,array('ulClass'=>'ul-unstyled-horizontal'))?>
			</div>
			
			<div id="footer-text">
				<p><?=$this->bal()->getConfig('bal.site.name')?> &copy; 2009
			</div>
		</div>
			
	</div>

</body>
</html>