<?php
	echo $this->doctype();
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlFront = $this->bal()->getBaseUrl('front');
	$User = $this->bal()->getUser();
?><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?= $this->headMeta()?>
    <?= $this->headTitle()?>
    <?
    // CSS
    $this->headLink()
		->appendStylesheet($baseUrlFront.'/styles/skin.css')
		;
    // Output
    echo $this->headLink();
    ?>
    <?= $this->headStyle()?>
	<link rel="Shortcut Icon" href="<?=$baseUrlFront?>/favicon.ico" type="image/x-icon" />
</head>
<body class="wp-admin js edit-pages-php">
    <? // headScript
    echo $this->headScript()
	    // JSON
	    ->offsetSetFile(1,'http://www.json.org/json2.js')
	    // jQuery
	    ->offsetSetFile(2,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js' : $baseUrl.'/scripts/jquery-1.3.2.min.js')
	    // Ajaxy
		//->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.history.js')->appendFile($baseUrl.'/scripts/ajaxy/js/jquery.ajaxy.js')
		// Application
	    //->offsetSetFile(5,$baseUrl.'/scripts/jquery.autogrow.js')
	    ->offsetSetFile(6,$baseUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetFile(7,$baseUrl.'/scripts/cms/front.js')
	    ;
    ?>
<body>
	<div id="main">
		
		<div id="header">
			<div id="logo"><h1><?=$this->bal()->getConfig('bal.site.name')?></h1></div>
			
			<div id="nav-top">
				<ul class="ul-unstyled-horizontal">
					<li><a href="#">Home</a> |</li>
					<li><a href="#">Events</a> |</li>
					<li><a href="#">Contact Us</a></li>
				</ul>
			</div>
			
			<div class="clear"></div>
		</div>
		
		<div id="nav-main">
			<ul class="ul-unstyled-horizontal">
				<li><a href="#">Home</a></li>
				<li><a href="#">Events</a></li>
				<li><a href="#">Contact Us</a></li>
			</ul>
		</div>
		
		<div id="content-wrap">
			<?=$this->layout()->content?>
		</div>
		
		<div id="footer">
			<div id="footer-links">
				<ul class="ul-unstyled-horizontal">
					<li><a href="#">Safe Shopping Guarantee</a></li>
					<li><a href="#">Customer Service</a></li>
					<li><a href="#">About Us</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Jobs</a></li>
				</ul>
			</div>
			
			<div id="footer-text">
				<p><?=$this->bal()->getConfig('bal.site.name')?> &copy; 2009 | <a href="#">Privacy Policy</a> | <a href="#">Terms Of Use</a></p>
			</div>
		</div>
			
	</div>

</body>
</html>