<?
	# Doctype
	echo $this->doctype();
	
	# Prepare
	$View = $this;
	$Message = delve($View,'Message');
	$this->url()->renege('route','app');

	# Prepare Relations
	$By		= delve($Message,'By');
	$For	= delve($Message,'For');
	
	# Prepare Urls
	$rootUrl		= $View->app()->getRootUrl();
	$baseUrl		= $View->app()->getBaseUrl(true);
	$Message_url	= $rootUrl.$View->url()->message($Message)->toString();
	$By_url			= delve($By,'id') ? $rootUrl.$View->url()->user($By)->toString() : $rootUrl;
	$For_url		= delve($For,'id') ? $rootUrl.$View->url()->user($For)->toString() : $rootUrl;
	
	# Prepare Params
	$params				= array();
	$params['Message']	= is_array($Message) ? $Message : $Message->toArray();
	$params['by'] 		= delve($By,'fullname','System');
	$params['for'] 		= delve($For,'fullname','System');
	
	# Apply URLs
	$params['rootUrl'] 		= $rootUrl;
	$params['baseUrl'] 		= $baseUrl;
	$params['Message_url'] 	= $Message_url;
	$params['By_url'] 		= $By_url;
	$params['For_url'] 		= $For_url;
?>
<html>
<head>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
</head>
<body class="email">
	<div class="email-wrapper">
		<div class="email-header">
			<?=$this->locale()->translate('message-header',$params)?>
		</div>
		<div class="email-body">
			<div class="email-from"><?=$this->locale()->translate('message-from',$params)?></div>
			<div class="email-title"><?=$this->locale()->translate('message-title',$params)?></div>
			<div class="email-description"><?=$this->locale()->translate('message-description',$params)?></div>
		</div>
		<div class="email-footer">
			<?=$this->locale()->translate('message-footer',$params)?>
		</div>
	</div>
</body>
</html><?