<?php
	// Doctype
	echo $this->doctype();
	// URLs
	$baseUrl = $this->app()->getBaseUrl();
	$contentUrl = $this->content()->getContentUrl($this->ContentArray);
	$unsubscribeUrl = $this->url(array('action'=>'unsubscribe'),'app',true);
?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
</head>
<body class="email">
	<div class="email-wrapper">
		<div class="email-header">
			<p>You're receiving this email because it matches your subscription prefrences on <a href="<?=$baseUrl?>">MyDance.com.au</a>.</p>
			<p>Having trouble reading this email? <a href="<?=$contentUrl?>">View it on your browser</a>. Not interested anymore? <a href="<?=$unsubscribeUrl?>">Unsubscribe Instantly</a>.</p>
		</div>
		<div class="email-body">
			<h1 class="email-title"><?=$this->ContentArray['title']?></h1>
			<div class="email-content">
				<?=$this->ContentArray['content_rendered']?>
			</div>
		</div>
		<div class="email-footer">
			<p>myDance.com.au... tagline asdasd asd asd</p>
		</div>
	</div>
</body>
</html>