<?php

/**
 * BalPermissionTemplate
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $code
 * @property Doctrine_Collection $PermissionGroupList
 * @property Doctrine_Collection $PermissionGroupPermission
 * @property Doctrine_Collection $PermissionUser
 * @property Doctrine_Collection $UserList
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BalPermissionTemplate extends BalTemplate
{
    public function setTableDefinition()
    {
        $this->setTableName('permission');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('code', 'string', 50, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        $this->hasMany('BalPermissionGroupTemplate as PermissionGroups', array(
			'refClass' 	=> 'BalPermissionGroupPermissionTemplate',
			'local' 	=> 'permission_id',
			'foreign' 	=> 'permissiongroup_id'
		));

        $this->hasMany('BalPermissionGroupPermissionTemplate', array(
			'local' 	=> 'id',
			'foreign' 	=> 'permission_id'
        ));
    }
}