<?php

/**
 * BalPermissionGroupPermissionTemplate
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property integer $permissiongroup_id
 * @property integer $permission_id
 * @property PermissionGroup $PermissionGroup
 * @property Permission $Permission
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BalPermissionGroupPermissionTemplate extends BalTemplate
{
    public function setTableDefinition()
    {
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('permissiongroup_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '2',
             ));
        $this->hasColumn('permission_id', 'integer', 2, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        $this->hasOne('BalPermissionGroupTemplate', array(
             'local' => 'permissiongroup_id',
             'foreign' => 'id'));

        $this->hasOne('BalPermissionTemplate', array(
             'local' => 'permission_id',
             'foreign' => 'id'));
    }
}