<?php

/**
 * BalPermissionGroupTemplate
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $code
 * @property Doctrine_Collection $PermissionList
 * @property Doctrine_Collection $PermissionGroupPermission
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BalPermissionGroupTemplate extends BalTemplate
{
    public function setTableDefinition()
    {
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'unsigned' => true,
             'length' => '2',
             ));
        $this->hasColumn('code', 'string', 15, array(
             'type' => 'string',
             'notblank' => true,
             'unique' => true,
             'length' => '15',
             ));
    }

    public function setUp()
    {
        $this->hasMany('BalPermissionTemplate as Permissions', array(
             'refClass'	=> 'BalPermissionGroupPermissionTemplate',
             'local' 	=> 'permissiongroup_id',
             'foreign' 	=> 'permission_id'
        ));

        $this->hasMany('BalPermissionGroupPermissionTemplate', array(
             'local' 	=> 'id',
             'foreign' 	=> 'permissiongroup_id'
        ));
    }
}