<?php

/**
 * Template
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6365 2009-09-15 18:22:38Z jwage $
 */
class Template extends BaseTemplate
{

	public function postSave ( Doctrine_Event $Event )
	{
		// Prepare
		$Invoker = $Event->getInvoker();
		$save = false;
		
		// Tags
		$tags = array();
		foreach ( $Invoker['Tags'] as $Tag ) {
			$tags[] = $Tag['name'];
		}
		$tags = implode($tags, ', ');
		if ( $Invoker->tagstr != $tags ) {
			$Invoker->tagstr = $tags;
			$save = true;
		}
		
		// Author
		if ( !empty($Invoker->Author) && $Invoker->Author->exists() ) {
			$author = $Invoker->Author->displayname;
			if ( $Invoker->authorstr != $author ) {
				$Invoker->authorstr = $author;
				$save = true;
			}
		}
		
		// Save
		if ( $save ) {
			$Invoker->save();
		}
		
		// Done
		return true;
	}
	
}