<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class User extends BaseUser
{
	/** Checks if we have this permission */
	public function hasPermission ( $code ) {
		// Prepare
		$this->loadReferenceInit('PermissionList');
		$PermissionList = $this->PermissionList;
		$result = false;
		// Seek
		foreach ( $PermissionList as $Permission ) {
			if ( $code === $Permission->get('code') ) {
				$result = true;
				break;
			}
		}
		// Exhausted
		return $result;
	}
}