<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6508 2009-10-14 06:28:49Z jwage $
 */
class User extends BaseUser
{
	
	/** Set the PermissionGroup for a User (clear others) */
	public function setPermissionGroup($permissiongroup){
		// Clear Relation
		$this->unlink('PermissionGroup');
		$this->link('PermissionGroup', $permissiongroup);
		// Done
		return true;
	}
	
	/*
	public function linkPermissionGroup($permissiongroup){
		// Fetch
		die($permissiongroup);
		$PermissionGroup = null;
		if ( is_numeric($permissiongroup) ) {
			$PermissionGroup = Doctrine::getTable('PermissionGroup')->find($permissiongroup);
		} else {
			$PermissionGroup = Doctrine::getTable('PermissionGroup')->findOneByCode($permissiongroup);
		}
		
	}
	*/
	
	/** Checks if the User has a certain Permission */
	public function hasPermission ( $code ) {
		// Prepare
		$this->loadReferenceInit('PermissionList');
		$PermissionList = $this->PermissionList;
		$result = false;
		// Seek
		foreach ( $PermissionList as $Permission ) {
			if ( $code === $Permission->get('code') ) {
				$result = true;
				break;
			}
		}
		// Exhausted
		return $result;
	}
}