<?
	$baseUrl = $this->bal()->getBaseUrl();
?>
<div id="content-search" class="content">
	<h2>
		Search: <?=$this->search?>
	</h2>
	<div id="content-content" class="content-content">
	
		<div class="contentlist">
			<? foreach ( $this->ContentList as $Content ) : ?>
				<div class="contentlist-content">
					<h3><a href="<?=$this->content()->getUrl($Content)?>" title="<?=$Content->title?>"><?=$Content->title?></a></h3>
					<div class="contentlist-content-content">
						<?=$this->content()->renderDescription($Content)?>
					</div>
				</div>
			<? endforeach; ?>
		</div>
		
	</div>
</div>