<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
?><div class="eventlist">
	<?
		$Lists = array(array(
			'code' => 'future',
			'title' => 'Upcoming Events',
			'list' => $this->EventsFuture
		),array(
			'code' => 'past',
			'title' => 'Past Events',
			'list' => $this->EventsPast
		));
		foreach ( $Lists as $List ) :
			$code = $List['code'];
			$title = $List['title'];
			$EventList = $List['list']; ?>
				<div class="eventlist-<?=$code?>">
					<? if ( count($EventList) ) : ?>
						<div class="eventlist-title"><h3><?=$title?>:</h3></div>
						<? foreach ( $EventList as $Content ) :
							$contentUrl = $this->url()->content($Content)->toString();
							?>
							<div class="eventlist-content">
								<h3>
									<a href="<?=$contentUrl?>" title="<?=$Content->title?>">
										<?=$this->locale()->date($Content->event_start_at).' - '.$Content->title?>
									</a>
								</h3>
								<div class="eventlist-content-content">
									<?=Content::renderDescription($Content)?>
								</div>
							</div>
						<? endforeach; ?>
					<? endif; ?>
				</div>
			<?
		endforeach;
	?>
</div>