<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$title = !empty($this->title) ? $this->title : 'Popular Tags';
?>
<div class="widget widget-taglist">
	<div class="widget-header">
		<h3><?=$title?></h3>
	</div>
	<? foreach ( $this->TagList as $Tag ) :
		$tag = $Tag->name;
		$tagUrl = $this->url()->search($tag)->toString();
		?>
		<div class="widget-content">
			<h4 class="widget-content-header">
				<a rel="nofollow" href="<?=$tagUrl?>" title="<?=$tag?>">
					<?=$tag?>
				</a>
			</h4>
		</div>
	<? endforeach; ?>
	<div class="clear"></div>
</div>