#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$dir = dirname(__FILE__);
chdir($dir);

$boostrap = $run = false;
require_once($dir.'/../public/index.php');
$Application->getBootstrap()->bootstrap('doctrine');
		
// Load Options
$doctrineOptions = $Application->getOption('doctrine');

// Load Cli
$Cli = new Doctrine_Cli($doctrineOptions);
$Cli->run($_SERVER['argv']);