#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$dir = dirname(__FILE__);
chdir($dir);

$boostrap = $run = false;
require_once($dir.'/../index.php');
$Application->getBootstrap()->bootstrap('doctrine');
		
// Load Config
$config = array();
$config['data'] = $Application->getOption('data');

// Apply Changes
$config['doctrine'] = $config['data'];
$config['doctrine']['data_dump_path'] = $config['doctrine']['dump_path'];
$config['doctrine']['data_fixtures_path'] = $config['doctrine']['fixtures_path'];

// Load Cli
$Cli = new Doctrine_Cli($config['doctrine']);
$Cli->run($_SERVER['argv']);