#!/usr/bin/env php
<?php
# Load
if ( empty($GLOBALS['Application']) ) {
	# Bootstrap
	require_once(dirname(__FILE__).'/bootstrapr.php');
	$Bootstrapr = Bootstrapr::getInstance();
	$Bootstrapr->bootstrap('zend-application');
}

# Load
$GLOBALS['Application']->bootstrap('ScriptDoctrine');

# App
Bal_App::getInstance($Application)->doctrineCli();
die;
