<?php
	echo $this->doctype();
	$baseUrl = $this->app()->getBaseUrl();
	$publicUrl = $this->app()->getPublicUrl();
	$frontUrl = $this->app()->getAreaUrl('front');
	$jqueryUiUrl = $publicUrl.'/scripts/jquery-ui-1.7.2';
	$jquerySparkleUrl = $publicUrl.'/scripts/jquery-sparkle';
	$User = $this->app()->getUser();
?><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <?= $this->headMeta()?>
    <?= $this->headTitle()?>
    <?
    // CSS
    $this->headLink()
		->appendStylesheet($frontUrl.'/styles/theme.css')
		;
    // Output
    echo $this->headLink();
    ?>
    <?= $this->headStyle()?>
</head>
<body class="">
    <? // headScript
    echo $this->headScript()
	    // JSON
	    ->offsetSetFile(1,'http://www.json.org/json2.js')
	    // jQuery
	    ->offsetSetFile(2,APPLICATION_ENV === 'production' ? 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js' : $publicUrl.'/scripts/jquery-1.3.2.min.js')
	    //
	    ->offsetSetFile(6,$jquerySparkleUrl.'/scripts/jquery.sparkle.js')
	    ->offsetSetFile(7,$publicUrl.'/scripts/balcms/front.js')
	    ;
    ?>
<body>
	<div id="main">
		
		<div id="header">
			<div id="logo"><h1><?=$this->app()->getConfig('bal.site.name')?></h1></div>
			
			<div id="nav-top" class="nav-action">
				<?=$this->navigation()->menu()->renderMenu($this->NavigationActions,array('ulClass'=>'ul-unstyled-horizontal'))?>
			</div>
			
			<div id="nav-search" class="nav-action">
				<form action="<?=$this->url(array('action'=>'search'),'app',true)?>" method="GET" >
					<label for="search">Search</label>
					<input type="text" name="search" id="search" title="Search query" class="sparkle-hint"  />
				</form>
			</div>
			
			<div id="nav-subscribe" class="nav-action">
				<form action="<?=$this->url(array('action'=>'subscribe'),'app',true)?>" method="POST" >
					<label for="email">Newsletter</label>
					<input type="text" name="email" id="email" title="Your email" class="sparkle-hint"  />
				</form>
			</div>
			
			<div class="clear"></div>
		</div>
		
		<div id="nav-main">
			<?=$this->navigation()->menu()->renderMenu($this->NavigationMenu,array('ulClass'=>'ul-unstyled-horizontal'))?>
		</div>
		
		<div id="content-wrap">
			<?=$this->layout()->content?>
		</div>
		
		<div id="footer">
			<div id="footer-links">
				<?=$this->navigation()->menu()->renderMenu($this->NavigationFooter,array('ulClass'=>'ul-unstyled-horizontal'))?>
			</div>
			
			<div id="footer-text">
				<p><?=$this->app()->getConfig('bal.site.name')?> &copy; 2009
			</div>
		</div>
			
	</div>
	
	<?
		$analyticsCode = $this->app()->getConfig('bal.analytics.code');
		if ( $analyticsCode ) : ?>
			<script type="text/javascript">
			//<![CDATA[
			var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
			document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
			//]]>
			</script><script type="text/javascript">
			//<![CDATA[
			var pageTracker = _gat._getTracker("<?=$analyticsCode?>");
			pageTracker._initData();
			pageTracker._trackPageview();
			//]]>
			</script>
			<?
		endif;
	?>
	
</body>
</html>