<?
	$baseUrl = $this->bal()->getBaseUrl();
	$baseUrlBack = $this->bal()->getBaseUrl('back');
?>
<textarea name="content" tabindex="2" id="content">
	Welcome to &lt;a href="http://wordpress.com/"&gt;WordPress.com&lt;/a&gt;. This is your first post. Edit or delete it and start blogging!
</textarea>
<script type="text/javascript">
	$(function(){
		$('#content').editor({
			script_url: '<?=$baseUrl?>/scripts/tiny_mce/tiny_mce.js'
		});
	});
</script>