<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$Oembed = delve($this,'Oembed');
	$title = $Oembed->title;
	$author = $Oembed->author_name;
	$video = html_entity_decode($Oembed->html);
?>
<section class="widget widget-vimeo section">
    <header class="widget-header section-header header">
        <h1><span class="title"><?=$title?></span></h1>
		<h2><span class="author"><?=$author?></span></h2>
    </header>
    <div class="widget-content">
		<?=$video?>
    </div>
</section>