<?php
	# Url
	$baseFullUrl = $this->app()->getBaseUrl(true);
	$baseUrl = $this->app()->getBaseUrl();
	$this->url()->renege('route','back');
?>
<div id="login">
	<h1><a title="Powered by balCMS" href="<?=$this->url()->route('balcmshome')?>">balCMS</a></h1>
	
	<?=$this->log()->render()?>
	
	<form method="post" action="<?=$this->url()->action('login')?>" id="login-form">
		<p>
			<label>
				Username<br/>
				<input type="text" tabindex="10" size="20" value="" class="input text" id="login-username" name="login[username]"/>
			</label>
		</p>
		<p>
			<label>
				Password<br/>
				<input type="password" tabindex="20" size="20" value="" class="input text" id="login-password" name="login[password]"/>
			</label>
		</p>
		<p id="forgetmenot">
			<label><input type="checkbox" tabindex="90" value="forever" id="login-remember" name="login[remember]"/> Remember Me</label>
		</p>
		<p id="loginsubmit">
			<input type="submit" tabindex="100" value="Log In" class="button-primary" id="wp-submit"/>
		</p>
		<div class="clear"></div>
	</form>
	
	<p id="nav">
		<a href="<?=$this->url()->route('balcmshome')?>">Learn More</a> |
		<a href="<?=$this->url()->route('balcmshelp')?>" class="gsfn">Provide Feedback</a>
	</p>
	
	<p id="backtoblog"><a title="Are you lost?" href="<?=$baseFullUrl?>">&larr; Back to <?=$this->app()->getConfig('bal.site.name')?></a></p>
	
</div>