<?php
	# Url
	$baseFullUrl = $this->app()->getBaseUrl(true);
	$baseUrl = $this->app()->getBaseUrl();
	$this->url()->renege('route','back');
?>
<div id="login">
	<h1 id="login-heading"><a title="Powered by balCMS" href="<?=$this->url()->route('balcmshome')?>">balCMS</a></h1>
	
	<?=$this->log()->render()?>
	
	<div id="login-box">
		<form method="post" action="<?=$this->url()->action('login')?>" id="login-form">
			<p>
				<label>
					Username<br/>
					<?=$this->formText('login[username]')?>
				</label>
			</p>
			<p>
				<label>
					Password<br/>
					<?=$this->formPassword('login[password]')?>
				</label>
			</p>
			<p id="login-remember-wrap">
				<label for="login-remember"><?=$this->formBoolean('login[remember]')?> Remember Me</label>
			</p>
			<p id="login-submit-wrap">
				<?=$this->formSubmit('login[submit]', 'Log In', array('class'=>'button-primary'))?>
			</p>
			<div class="clear"></div>
		</form>
	</div>
	
	<div id="login-nav">
		<a href="<?=$this->url()->route('balcmshome')?>">Learn More</a> |
		<a href="<?=$this->url()->route('balcmshelp')?>" class="gsfn">Provide Feedback</a>
	</div>
	
	<div id="login-back">
		<a title="Are you lost?" href="<?=$baseFullUrl?>">&larr; Back to <?=$this->app()->getConfig('bal.site.name')?></a>
	</div>
	
</div>