<ul id="adminmenu">
<?
$id_prefix = 'menu-';
$first = true;
foreach ($this->container as $Page ) :
	$label = $Page->label;
	// Checks
	$active = false;
	$class = array($Page->class);
	$sep = $label === '---';
	$children = count($Page);
	if ( $sep ) {
		// Sep
		$class[] = 'wp-menu-separator';
		// Position
		$first = true;
	} else {
		// Content
		echo '<!-- ['.$label.'] -->', PHP_EOL;
		// Position
		if ( $first ) {
			$class[] = 'wp-first-item';
			$class[] = 'menu-top-first';
			$first = false;
		}
		// Active
		$active = $Page->isActive(false);
		if ( $active ) {
			if ( $children ) {
				$class[] = 'wp-menu-open';
				$class[] = 'wp-has-current-submenu';
			}
		}
		if ( $children ) {
			$class[] = 'wp-has-submenu';
		}
		// Normal
		$class[] = 'menu-top';
		// Display
	}

	// Display
	$li = $this->HtmlElement(
		'li',
		true,
		array('id'=>($Page->id?$id_prefix.$Page->id:''),'class'=>implode(' ',$class)),
		true,
		false
	);
	echo $li;
	// Handle
	if ( $sep ) {
		// Sep
		?><a class="separator" href="#">
			<br />
		</a><?
	} else {
		// Content
		?><div class="wp-menu-image">
			<a>
				<br/>
			</a>
		</div>
		<div class="wp-menu-toggle">
			<br/>
		</div><?
		$Page->class = 'menu-title';
		$Page->id = null;
		$page = html_entity_decode($this->navigation()->menu()->htmlify($Page)).PHP_EOL;
		echo $page;
		// Submenu
		if ( $children ) : ?>
			<div class="wp-submenu">
				<div class="wp-submenu-head">
					<?=$Page->label?>
				</div>
				<ul><?
					$first_ = true;
					foreach ( $Page as $SubPage ) :
						$class = array($SubPage->class);
						// Active
						$active = $SubPage->isActive(false);
						if ( $active ) {
							$class[] = 'current';
						}
						// Position
						if ( $first_ ) {
							$class[] = 'wp-first-item';
							$first_ = false;
						}
						// Prepare
						$SubPage->id = null;
						$subpage = html_entity_decode($this->navigation()->menu()->htmlify($SubPage)).PHP_EOL;
						// Wrap
						$li = $this->HtmlElement(
							'li',
							$subpage,
							array('id'=>($SubPage->id?$id_prefix.$SubPage->id:''),'class'=>implode(' ',$class))
						);
						// Display
						echo $li.PHP_EOL;
					endforeach;?>
				</ul>
			</div><?
		endif;
	}

	// Display
	echo '</li>', PHP_EOL;

endforeach; ?>
</ul>
<script type="text/javascript">
	$(function(){
		var $menu = $('#adminmenu');
		$menu.find('.wp-has-submenu .wp-menu-toggle').click(function(){
			var $toggle = $(this);
			var $menu = $toggle.parent('.menu-top').toggleClass('wp-menu-open');
		});
		$menu.find('.wp-menu-separator .separator').click(function(){
			$(document.body).toggleClass('folded');
		});
	});
</script>