<?
	# URLs
	$back_url = $this->app()->getAreaUrl('back');
	$front_url = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	
	# Extract
	$FileList = delve($this,'FileList');
	
	# Title
	$this->headTitle()->append('Media');
	$this->headTitle()->append('Files');
?>
<div class="wrap">
    <!-- Actions -->
	<form action="<?=$this->url()->action('media-file-list')?>" method="post" enctype="multipart/form-data">
		<!-- Edit Button -->
	    <div id="icon-upload" class="icon32">
	        <br/>
	    </div>
		<!-- Header -->
	    <h2>
			File Library
			<a class="button add-new-h2" id="file-add">Add New File</a>
			<?=$this->formFile('File[file]')?>
			<input type="submit" id="file-submit" class="hide" /><!-- not formSubmit due to difficulty porting limited params -->
			<script type="text/javascript">
				$(function(){
					var $file = $('#File-file'),
						$submit = $('#file-submit'),
						$add = $('#file-add');
					$file.change(function(){
						if ( $file.val() ) $submit.trigger('click');
					});
					var width = $add.width();
					$file.css('opacity',0).removeClass('hide').width(width+'px').css('margin-left',-width+'px');
				});
			</script>
		</h2>
	</form>
    <!-- Filters -->
    <form id="posts-filter" action="<?=$this->url()->action('media-file-list')->search()?>" method="post">
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="search-query">
                Search:
            </label>
			<?=$this->formText('search[query]',delve($this,'search.query'),array())?>
			<?=$this->formSubmit('search[submit]','Search',array('class'=>'button'))?>
        </p>
	</form>
    <!-- Listing -->
    <form action="<?=$this->url()->action('media-file-list')?>" method="get">
        <div class="clear">
        </div>
		<?=$this->log()->render()?>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="subscriber-list">
            	<? foreach ( $FileList as $_File ):
					$_File_id = delve($_File,'id');
					$_File_title = delve($_File,'title');
					$_File_type = delve($_File,'type');
					$_File_humantype = delve($_File,'humantype');
					$_File_code = delve($_File,'code');
					$_File_size = delve($_File,'size');
					$_File_Author = delve($_File,'Author');
					$_File_Author_displayname = delve($_File_Author,'displayname');
					$_File_url = $this->url()->file($_File)->toString();
					$_File_url_delete = $this->url()->action('media-file-delete')->item($_File)->toString();
					?>
            	<tr id="file-<?=$_File_id?>" class="<?=$this->cycle(array('','alternate'), 'ContentTreeArray')->next()?>">
					<td class="column-icon media-icon">
						<a title="View <?=$_File_title?>" href="<?=$_File_url?>">
							<? if ( $_File_type === 'image' ) : ?>
								<img height="60" title="<?=$_File_title?>" alt="" class="attachment-80x60" src="<?=$_File_url?>?h=60"/>
							<? else: ?>
								<img width="46" height="60" title="<?=$_File_title?>" alt="" class="attachment-80x60" src="<?=$back_url?>/images/files/<?=$_File_type?>.png"/>
							<? endif; ?>
						</a>
					</td>
					<td class="media column-media">
						<strong><a title="View <?=$_File_title?>" href="<?=$_File_url?>">
							<?=$_File_title?>
						</a></strong>
						<br/>
						<?=$_File_humantype?>
						<p></p>
						<div class="row-actions">
							<span class="delete">
								<a href="<?=$_File_url_delete?>" class="delete-action">Delete</a> |
							</span>
							<span class="view">
								<a rel="permalink" title="View <?=$_File_title?>" href="<?=$_File_url?>">View</a>
							</span>
						</div>
					</td>
                    <td class="tags column-author hide">
                    	<?=$_File_code?>
                    </td>
                    <td class="tags column-tags">
                    	<?=filesize_human($_File_size)?>
                    </td>
                    <td class="author column-author"><?
                        if ( empty($_File_Author) ) :
                        	echo 'Unkown';
                        else:
                        	$author = $_File_Author_displayname;
                        	$author_url = $this->url()->action('media-file-list')->search($author)->toString();
                        	echo '<a href="'.$author_url.'" title="View all files by '.$author.'">'.$author.'</a>';
                    	endif;
                    ?></td>
				</tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
</div>