<?
	# URLs
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	$this->url()->renege('route','back');
	
	# Extract
	$MediaList = delve($this,'MediaList');
	
	# Title
	$this->headTitle()->append('Media');
?>
<div class="wrap">
    <!-- Actions -->
	<form action="<?=$this->url()->action('media-list')?>" method="post" enctype="multipart/form-data">
		<!-- Edit Button -->
	    <div id="icon-upload" class="icon32">
	        <br/>
	    </div>
		<!-- Header -->
	    <h2>
			Media Library
			<a class="button add-new-h2" id="media-add">Add New Media</a>
			<?=$this->formFile('Media[file]')?>
			<input type="submit" id="media-submit" class="hide" /><!-- not formSubmit due to difficulty porting limited params -->
			<script type="text/javascript">
				$(function(){
					var $file = $('#Media-file'),
						$submit = $('#media-submit'),
						$add = $('#media-add');
					$file.change(function(){
						if ( $file.val() ) $submit.trigger('click');
					});
					var width = $add.width();
					$file.css('opacity',0).removeClass('hide').width(width+'px').css('margin-left',-width+'px');
				});
			</script>
		</h2>
	</form>
    <!-- Filters -->
    <form id="posts-filter" action="<?=$this->url()->action('media-list')->search()?>" method="post">
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="search-query">
                Search:
            </label>
			<?=$this->formText('search[query]',delve($this,'search.query'),array())?>
			<?=$this->formSubmit('search[submit]','Search',array('class'=>'button'))?>
        </p>
	</form>
    <!-- Listing -->
    <form action="<?=$this->url()->action('media-list')?>" method="get">
        <div class="clear">
        </div>
		<?=$this->log()->render()?>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="subscriber-list">
            	<? foreach ( $MediaList as $_Media ):
					$_Media_id = delve($_Media,'id');
					$_Media_title = delve($_Media,'title');
					$_Media_type = delve($_Media,'type');
					$_Media_humantype = delve($_Media,'humantype');
					$_Media_code = delve($_Media,'code');
					$_Media_size = delve($_Media,'size');
					$_Media_Author = delve($_Media,'Author');
					$_Media_Author_displayname = delve($_Media_Author,'displayname');
					$_Media_url = $this->url()->media($_Media)->toString();
					$_Media_url_delete = $this->url()->action('media-delete')->item($_Media)->toString();
					?>
            	<tr id="media-<?=$_Media_id?>" class="<?=$this->cycle(array('','alternate'), 'ContentTreeArray')->next()?>">
					<td class="column-icon media-icon">
						<a title="View <?=$_Media_title?>" href="<?=$_Media_url?>">
							<? if ( $_Media_type === 'image' ) : ?>
								<img height="60" title="<?=$_Media_title?>" alt="" class="attachment-80x60" src="<?=$_Media_url?>?h=60"/>
							<? else: ?>
								<img width="46" height="60" title="<?=$_Media_title?>" alt="" class="attachment-80x60" src="<?=$backUrl?>/images/files/<?=$_Media_type?>.png"/>
							<? endif; ?>
						</a>
					</td>
					<td class="media column-media">
						<strong><a title="View <?=$_Media_title?>" href="<?=$_Media_url?>">
							<?=$_Media_title?>
						</a></strong>
						<br/>
						<?=$_Media_humantype?>
						<p></p>
						<div class="row-actions">
							<span class="delete">
								<a href="<?=$_Media_url_delete?>" class="delete-action">Delete</a> |
							</span>
							<span class="view">
								<a rel="permalink" title="View <?=$_Media_title?>" href="<?=$_Media_url?>">View</a>
							</span>
						</div>
					</td>
                    <td class="tags column-author hide">
                    	<?=$_Media_code?>
                    </td>
                    <td class="tags column-tags">
                    	<?=filesize_human($_Media_size)?>
                    </td>
                    <td class="author column-author"><?
                        if ( empty($_Media_Author) ) :
                        	echo 'Unkown';
                        else:
                        	$author = $_Media_Author_displayname;
                        	$author_url = $this->url()->action('media-list')->search($author)->toString();
                        	echo '<a href="'.$author_url.'" title="View all media by '.$author.'">'.$author.'</a>';
                    	endif;
                    ?></td>
				</tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
</div>