<?
	// URLs
	$backUrl = $this->app()->getAreaUrl('back');
	$frontUrl = $this->app()->getAreaUrl('front');
	//
	$MediaList = delve($this,'MediaList');
	// Title
	$this->headTitle()->append('Media');
?>
<div class="wrap">
	<form action="<?=$this->url(array('action'=>'media-list'),'back',true)?>" method="post" enctype="multipart/form-data">
		<!-- Edit Button -->
	    <div id="icon-upload" class="icon32">
	        <br/>
	    </div>
		<!-- Header -->
	    <h2>
			Media Library
			<a class="button add-new-h2" id="media-add">Add New</a>
			<input type="file" id="media-file" name="media" class="hide" />
			<input type="hidden" name="MAX_FILE_SIZE" value="<?=filesize_from_human(ini_get('upload_max_filesize').'B')?>" />
			<span class="little"><?=$this->locale()->translate('file-upload-size',$this->locale()->filesize(filesize_from_human(ini_get('upload_max_filesize').'B')))?></span>
			<input type="submit" id="media-submit" class="hide" />
			<script type="text/javascript">
				$(function(){
					var $file = $('#media-file'),
						$submit = $('#media-submit'),
						$add = $('#media-add');
					$file.change(function(){
						if ( $file.val() ) $submit.trigger('click');
					});
					var width = $add.width();
					$file.css('opacity',0).removeClass('hide').width(width+'px').css('margin-left',-width+'px');
				});
			</script>
		</h2>
		<!-- Search -->
        <p class="search-box">
            <label class="screen-reader-text" for="page-search-input">
                Search:
            </label>
            <input id="page-search-input" name="search" type="text" />
            <input value="Search" class="button" type="submit" />
        </p>
        <div class="clear">
        </div>
		<!-- Content Table -->
        <table class="widefat page fixed" cellspacing="0">
        	<!-- Content Table: Heading -->
            <thead>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!--<th scope="col" id="cb" class="manage-column column-cb check-column" style="">
                        <input type="checkbox">
                    </th>-->
                    <th scope="col" class="manage-column column-icon"></th>
                    <th scope="col" class="manage-column column-media" style="">
                        File
                    </th>
                    <th scope="col" class="manage-column column-author hide" style="">
                        Filename
                    </th>
                    <th scope="col" class="manage-column column-tags" style="">
                        Size
                    </th>
                    <th scope="col" class="manage-column column-author" style="">
                        Author
                    </th>
                </tr>
            </tfoot>
			<!-- Content Table: Content -->
            <tbody id="subscriber-list">
            	<? foreach ( $MediaList as $_Media ):
					$_Media_id = delve($_Media,'id');
					$_Media_title = delve($_Media,'title');
					$_Media_type = delve($_Media,'type');
					$_Media_code = delve($_Media,'code');
					$_Media_size = delve($_Media,'size');
					$_Media_Author = delve($_Media,'Author');
					$_Media_Author_displayname = delve($_Media_Author,'displayname');
					$mediaUrl = $this->content()->getMediaUrl($Media);
					?>
            	<tr id="media-<?=$_Media_id?>" class="<?=$this->cycle(array('alternate',''), 'ContentTreeArray')->next()?>">
					<td class="column-icon media-icon">
						<a title="View <?=$_Media_title?>" href="<?=$mediaUrl?>">
							<? if ( $Media['type'] === 'image' ) : ?>
								<img height="60" title="<?=$_Media_title?>" alt="" class="attachment-80x60" src="<?=$mediaUrl?>?h=60"/>
							<? else: ?>
								<img width="46" height="60" title="<?=$Media['title']?>" alt="" class="attachment-80x60" src="<?=$backUrl?>/images/files/<?=$_Media_type?>.png"/>
							<? endif; ?>
						</a>
					</td>
					<td class="media column-media">
						<strong><a title="View <?=$_Media_title?>" href="<?=$mediaUrl?>">
							<?=$Media['title']?>
						</a></strong>
						<br/>
						<?=$Media['humantype']?>
						<p></p>
						<div class="row-actions">
							<span class="edit hide">
								<a href="<?=$this->url(array('action'=>'media-edit','media'=>$_Media_code),'back',true)?>">Edit</a> |
							</span>
							<span class="delete">
								<a href="<?=$this->url(array('action'=>'media-delete','media'=>$_Media_code),'back',true)?>" class="delete-action">Delete</a> |
							</span>
							<span class="view">
								<a rel="permalink" title="View <?=$_Media_title?>" href="<?=$mediaUrl?>">View</a>
							</span>
						</div>
					</td>
                    <td class="tags column-author hide">
                    	<?=$Media['code']?>
                    </td>
                    <td class="tags column-tags">
                    	<?=filesize_human($_Media_size)?>
                    </td>
                    <td class="author column-author"><?
                        if ( empty($_Media_Author) ) :
                        	echo 'Unkown';
                        else:
                        	$author = $_Media_Author_displayname;
                        	$author_url = $this->url(array(
                        		'action'=>'media-list',
                        		'search'=>$author
                        	), 'back', true);
                        	echo '<a href="'.$author_url.'" title="View all media by '.$author.'">'.$author.'</a>';
                    	endif;
                    ?></td>
				</tr>
				<? endforeach; ?>
            </tbody>
        </table>
    </form>
</div>