<ul id="adminmenu">
<?
$id_prefix = 'menu-';
$first = true;
foreach ($this->container as $Page ) :
	$label = $Page->label;
	// Checks
	$active = false;
	$class = array($Page->class);
	$sep = $label === '---';
	$children = count($Page);
	if ( $sep ) {
		// Sep
		$class[] = 'wp-menu-separator';
		// Position
		$first = true;
	} else {
		// Content
		echo '<!-- ['.$label.'] -->', PHP_EOL;
		// Position
		if ( $first ) {
			$class[] = 'wp-first-item';
			$class[] = 'menu-top-first';
			$first = false;
		}
		// Active
		$active = $Page->isActive(false);
		if ( $active ) {
			$class[] = 'wp-menu-open';
			if ( $children ) $class[] = 'wp-has-current-submenu';
		}
		if ( $children ) $class[] = 'wp-has-submenu';
		// Normal
		$class[] = 'menu-top';
		// Display
	}

	// Display
	echo '<li id="'.($Page->id?$id_prefix.$Page->id:'').'" class="'.implode(' ',$class).'" >';

	// Handle
	if ( $sep ) {
		// Sep
		?><a class="separator" href="#">
			<br />
		</a><?
	} else {
		// Content
		?><div class="wp-menu-image">
			<a href="http://localhost/wordpress/wp-admin/index.php">
				<br/>
			</a>
		</div>
		<div class="wp-menu-toggle">
			<br/>
		</div><?
		$Page->class = 'menu-title';
		echo html_entity_decode($this->navigation()->menu()->htmlify($Page)), PHP_EOL;
		// Submenu
		if ( $children ) : ?>
			<div class="wp-submenu">
				<div class="wp-submenu-head">
					<?=$Page->label?>
				</div>
				<ul><?
					$first_ = true;
					foreach ( $Page as $SubPage ) :
						$class = array($SubPage->class);
						// Active
						$active = $SubPage->isActive(false);
						if ( $active ) {
							$class[] = 'current';
						}
						// Position
						if ( $first_ ) {
							$class[] = 'wp-first-item';
							$first_ = false;
						}
						// Display
						echo '<li id="'.($SubPage->id?$id_prefix.$SubPage->id:'').'" class="'.implode(' ',$class).'" >';
						// Handle
						echo html_entity_decode($this->navigation()->menu()->htmlify($SubPage)), PHP_EOL;
						// Display
						echo '</li>', PHP_EOL;
					endforeach;?>
				</ul>
			</div><?
		endif;
	}

	// Display
	echo '</li>', PHP_EOL;

endforeach; ?>
</ul>