<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$username = delve($this,'flickr.person.username._content','');
	$realname = delve($this,'flickr.person.realname._content',$username);
	$profile_url =  delve($this,'flickr.person.profileurl._content','');
	$photos = delve($this,'flickr.photos.photo',array());
?>
<section class="widget widget-gallery section">
    <header class="widget-header section-header header">
        <h1><span class="title">Flickr Favorites: <a href="<?=$profile_url?>" title="<?=$realname?>"><?=$username?></a></span></h1>
    </header>
    <div class="widget-content">
		<div class="gallery flickr flickr-gallery">
			<ul class="images">
				<? foreach ( $photos as $photo ) : 
					require(dirname(__FILE__).'/_photo.phtml');
				endforeach; ?>
			</ul>
		</div>
    </div>
</section>