<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$title = delve($this,'flickr.gallery.title._content','');
	$photos = delve($this,'flickr.photos.photo',array());
?>
<section class="widget widget-gallery section">
    <header class="widget-header section-header header">
        <h1><span class="title">Flickr Gallery: <?=$title?></span></h1>
    </header>
    <div class="widget-content">
		<div class="gallery flickr flickr-gallery">
			<ul class="images">
				<? foreach ( $photos as $photo ) : 
					require(dirname(__FILE__).'/_photo.phtml');
				endforeach; ?>
			</ul>
		</div>
    </div>
</section>