<?
	# Prepare
	$this->url()->renege('route','front');
	# Extract
	$title = delve($this,'flickr.gallery.title','');
	$photos = delve($this,'flickr.photos.photo',array());
?>
<section class="widget widget-gallery section">
    <header class="widget-header section-header header">
        <h1><span class="title">Flickr Gallery: <?=$title?></span></h1>
    </header>
    <div class="widget-content">
		<div class="gallery flickr flickr-gallery">
			<ul class="images">
				<? foreach ( $photos as $photo ) :
					echo populate('<li class="image"><a href="$url_m" title="$title"><img src="$url_sq" title="$title" height="$height_sq" width="width_sq" /></a></li>', $photo);
				endforeach; ?>
			</ul>
		</div>
    </div>
</section>